apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orchestrator
  labels:
    app: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag }}"
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
            - name: REDIS_URL
              value: "redis://:{{ .Values.redis.auth.password }}@{{ .Release.Name }}-redis-master:6379/0"
          volumeMounts:
            - name: code-volume
              mountPath: /app
      volumes:
        - name: code-volume
          hostPath:
            path: /home/ubuntu/predator-analytics
            type: Directory
