apiVersion: apps/v1
kind: Deployment
metadata:
  name: adv-dvs
  labels:
    app: adv-dvs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adv-dvs
  template:
    metadata:
      labels:
        app: adv-dvs
    spec:
      containers:
        - name: adv-dvs
          image: {{ .Values.advDvs.image.repository }}:{{ .Values.advDvs.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 8002
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: adv-dvs-config
