{{- if .Values.security.networkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "predator.fullname" . }}-zero-trust
spec:
  endpointSelector:
    matchLabels:
      {{- include "predator.selectorLabels" . | nindent 6 }}
      app: core-api
  ingress:
    - fromEndpoints:
        - matchLabels:
            {{- include "predator.selectorLabels" . | nindent 12 }}
            app: frontend
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
    - toEndpoints:
        - matchLabels:
            app: postgresql
    - toEndpoints:
        - matchLabels:
            {{- include "predator.selectorLabels" . | nindent 12 }}
            app: graph-service
{{- end }}
