apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: core-api-zero-trust
spec:
  endpointSelector:
    matchLabels:
      app: core-api
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: frontend
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
    - toEndpoints:
        - matchLabels:
            app: postgresql
    - toEndpoints:
        - matchLabels:
            app: graph-service
