apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "predator.fullname" . }}-core-api
spec:
  replicas: {{ .Values.coreApi.replicaCount }}
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
      steps:
        - setWeight: 20
        - pause: {duration: 5m}
        - setWeight: 50
        - pause: {duration: 5m}
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
        - name: core-api
          image: "{{ .Values.coreApi.image.repository }}:{{ .Values.coreApi.image.tag }}"
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.coreApi.resources | nindent 12 }}
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: url
