apiVersion: v1
kind: Service
metadata:
  name: {{ include "predator.fullname" . }}-core-api
  labels:
    {{- include "predator.labels" . | nindent 4 }}
    app: core-api
spec:
  type: {{ .Values.coreApi.service.type }}
  ports:
    - port: {{ .Values.coreApi.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "predator.selectorLabels" . | nindent 4 }}
    app: core-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "predator.fullname" . }}-graph-service
  labels:
    {{- include "predator.labels" . | nindent 4 }}
    app: graph-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.graphService.service.port }}
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    {{- include "predator.selectorLabels" . | nindent 4 }}
    app: graph-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "predator.fullname" . }}-frontend
  labels:
    {{- include "predator.labels" . | nindent 4 }}
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3030
      protocol: TCP
      name: http
  selector:
    {{- include "predator.selectorLabels" . | nindent 4 }}
    app: frontend

