
apiVersion: v1
kind: ResourceQuota
metadata:
  name: predator-quota
  namespace: predator-analytics
spec:
  hard:
    requests.cpu: "16"
    requests.memory: "32Gi"
    limits.cpu: "24"
    limits.memory: "48Gi"
    pods: "60"
    services: "25"
    persistentvolumeclaims: "20"
    count/jobs.batch: "10"
