import ast
import logging
import os
import aiofiles
from litellm import acompletion

logger = logging.getLogger("autonomous_agents.connector_agent")

LITELLM_URL = os.getenv("LITELLM_URL", "http://litellm:4000")
LITELLM_KEY = os.getenv("LITELLM_KEY", "sk-predator")

# Using Qwen3-Coder as defined in the AGENTS.md for surgical coding
MODEL_NAME = "openai/Qwen3-Coder-Next"

class ConnectorAgent:
    """Agent that generates code for data ingestion (Harvesters) using LLM and validates it."""
    
    def __init__(self):
        self.output_dir = "/Users/Shared/Predator_60/services/ingestion-worker/app/harvesters/auto/"
        os.makedirs(self.output_dir, exist_ok=True)
        
    async def generate_connector(self, source_info: dict) -> dict:
        """
        Generates a python harvester class for a given source.
        """
        url = source_info.get("url")
        source_type = source_info.get("type", "api")
        schema_sample = source_info.get("schema_sample", "")
        
        logger.info(f"ConnectorAgent: Starting generation for {url}")
        
        prompt = f"""
        You are an expert Data Engineer AI. Write a complete Python class for a data scraper (Harvester).
        The source is: {url}
        Type: {source_type}
        Sample payload schema: {schema_sample}
        
        Requirements:
        1. Class name should be generated based on the domain (e.g. ExampleComHarvester).
        2. Must have an `async def run(self):` method.
        3. Must use `httpx.AsyncClient`.
        4. Must import and use `from predator_common.logging import get_logger`.
        5. Assume `self.neo4j = Neo4jSink()` and `self.minio = MinioClient()` are available and instantiated in `__init__`.
        6. Provide ONLY the raw Python code, no markdown wrapping, no explanations.
        """
        
        try:
            # LiteLLM invocation
            response = await acompletion(
                model=MODEL_NAME,
                messages=[{"role": "user", "content": prompt}],
                api_base=LITELLM_URL,
                api_key=LITELLM_KEY,
                temperature=0.1
            )
            
            generated_code = response.choices[0].message.content.strip()
            
            # Clean up markdown if model ignored instructions
            if generated_code.startswith("```python"):
                generated_code = generated_code.replace("```python", "").replace("```", "").strip()
                
            # AST Validation
            if not self._validate_code(generated_code):
                raise ValueError("Generated code failed AST validation (Syntax Error).")
                
            class_name = self._extract_class_name(generated_code)
            filename = f"auto_{class_name.lower()}.py"
            filepath = os.path.join(self.output_dir, filename)
            
            async with aiofiles.open(filepath, mode="w") as f:
                await f.write(generated_code)
                
            logger.info(f"ConnectorAgent: Successfully generated and saved {filename}")
            
            return {
                "status": "success",
                "file": filepath,
                "class_name": class_name
            }
            
        except Exception as e:
            logger.error(f"ConnectorAgent: Error generating connector: {e}", exc_info=True)
            return {
                "status": "error",
                "reason": str(e)
            }
            
    def _validate_code(self, code: str) -> bool:
        """Validates that the generated code is syntactically valid Python."""
        try:
            ast.parse(code)
            return True
        except SyntaxError as e:
            logger.error(f"AST Validation Failed: {e}")
            return False

    def _extract_class_name(self, code: str) -> str:
        """Extracts the first class name defined in the code using AST."""
        tree = ast.parse(code)
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                return node.name
        return "AutoGeneratedHarvester"
