apiVersion: v2
name: predator-nvidia
description: Helm chart for Predator Analytics on NVIDIA Server (lab-gpu)
type: application
version: 19.0.0
appVersion: "19.0.0"

dependencies:
  - name: postgresql
    version: "~15.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "~18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled