enabled: true
image:
  repository: "opensearchproject/opensearch"
  tag: "2.11.0"
persistence:
  size: 20Gi

resources:
  requests:
    cpu: 100m
    memory: 2Gi
  limits:
    cpu: 500m
    memory: 2Gi

env:
  DISABLE_SECURITY_PLUGIN: "true"
  OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
  discovery.type: "single-node"
