enabled: true
image:
  repository: "opensearchproject/opensearch"
  tag: "2.11.0"
persistence:
  size: 20Gi

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

env:
  DISABLE_SECURITY_PLUGIN: "true"
  OPENSEARCH_JAVA_OPTS: "-Xms256m -Xmx256m"
  discovery.type: "single-node"
