"""
Git Auto-Committer - Automatically commits successful improvements
"""
import subprocess
import logging
from datetime import datetime
from typing import Dict, Any

logger = logging.getLogger("agents.git_committer")

class GitAutoCommitter:
    def __init__(self):
        self.repo_path = "/app"
        self.remote_name = "origin"
        self.branch_name = "auto-improve"

    async def commit_improvement(self,
                                 description: str,
                                 files_changed: list,
                                 metadata: Dict[str, Any]) -> bool:
        """Automatically commit and push improvement"""
        try:
            # Stage files
            for file in files_changed:
                await self._run_git(["add", file])

            # Create commit message
            commit_msg = self._generate_commit_message(description, metadata)

            # Commit
            await self._run_git(["commit", "-m", commit_msg])

            # Push to auto-improve branch
            await self._run_git(["push", self.remote_name, f"HEAD:{self.branch_name}"])

            logger.info(f"✅ Auto-committed: {description}")
            return True

        except Exception as e:
            logger.error(f"Git commit failed: {e}")
            return False

    async def _run_git(self, args: list) -> str:
        """Run git command"""
        cmd = ["git", "-C", self.repo_path] + args
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)

        if result.returncode != 0:
            raise Exception(f"Git command failed: {result.stderr}")

        return result.stdout

    def _generate_commit_message(self, description: str, metadata: Dict) -> str:
        """Generate detailed commit message"""
        cycle = metadata.get("cycle", 0)
        improvements = metadata.get("improvements", [])

        msg = f"""🤖 Auto-Improvement #{cycle}: {description}

Generated by: Predator Orchestrator v23.0
Timestamp: {datetime.now().isoformat()}
Council Decision: {metadata.get('council_decision', 'APPROVED')}

Changes:
"""
        for imp in improvements:
            msg += f"- {imp}\n"

        msg += f"\nHealth Score: {metadata.get('health_score', 'N/A')}"
        msg += "\nCo-authored-by: Orchestrator <orchestrator@predator.ai>"

        return msg
