#!/usr/bin/env python3.12
"""
Git Auto-Committer - Automatically commits successful improvements
"""
import subprocess
import logging
from datetime import datetime
from typing import Dict, Any

logger = logging.getLogger("agents.git_committer")

class GitAutoCommitter:
    def __init__(self):
        self.repo_path = "/app"
        self.remote_name = "origin"
        self.branch_name = "auto-improve"

    async def commit_improvement(self,
                                 description: str,
                                 files_changed: list,
                                 metadata: Dict[str, Any]) -> bool:
        """Automatically commit improvement locally"""
        try:
            # Stage files
            if not files_changed:
                await self._run_git(["add", "."])
            else:
                for file in files_changed:
                    await self._run_git(["add", file])

            # Create commit message
            commit_msg = self._generate_commit_message(description, metadata)

            # Commit (allow empty to avoid failure if no changes detected by git)
            try:
                await self._run_git(["commit", "--allow-empty", "-m", commit_msg])
            except Exception as e:
                if "nothing to commit" in str(e).lower():
                    logger.info("Nothing to commit (clean state)")
                    return True
                raise e

            # Push is OPTIONAL and should not block the cycle
            try:
                # Only push if remote exists and we are configured to push
                await self._run_git(["push", self.remote_name, f"HEAD:{self.branch_name}"])
                logger.info("✅ Pushed to remote branch")
            except Exception as e:
                 logger.debug(f"ℹ️ Skipping push: {e}")

            logger.info(f"✅ Auto-committed locally: {description}")
            return True

        except Exception as e:
            logger.error(f"Git commit failed: {e}")
            return False

    async def _run_git(self, args: list) -> str:
        """Run git command"""
        cmd = ["git", "-C", self.repo_path] + args
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)

        if result.returncode != 0:
            raise Exception(f"Git command failed: {result.stderr}")

        return result.stdout

    def _generate_commit_message(self, description: str, metadata: Dict) -> str:
        """Generate detailed commit message"""
        cycle = metadata.get("cycle", 0)
        improvements = metadata.get("improvements", [])

        msg = f"""🤖 Auto-Improvement #{cycle}: {description}

Generated by: Predator Orchestrator v23.0
Timestamp: {datetime.now().isoformat()}
Council Decision: {metadata.get('council_decision', 'APPROVED')}

Changes:
"""
        for imp in improvements:
            msg += f"- {imp}\n"

        msg += f"\nHealth Score: {metadata.get('health_score', 'N/A')}"
        msg += "\nCo-authored-by: Orchestrator <orchestrator@predator.ai>"

        return msg
