# Skaffold configuration for local Kubernetes development
# Run: skaffold dev (for hot-reload) or skaffold run (for one-time deploy)

apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: predator-analytics

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: predator/ua-sources
      context: ./ua-sources
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "app/**/*.py"
            dest: /app/app
    - image: predator/frontend
      context: ./frontend
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.tsx"
          - "**/*.ts"
          - "**/*.css"

deploy:
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/configmaps.yaml
      - k8s/secrets.yaml
      - k8s/storage.yaml
      - k8s/postgres.yaml
      - k8s/redis.yaml
      - k8s/opensearch.yaml
      - k8s/qdrant.yaml
      - k8s/minio.yaml
      - k8s/backend.yaml
      - k8s/celery.yaml
      - k8s/frontend.yaml
      - k8s/ingress.yaml

profiles:
  - name: dev
    activation:
      - kubeContext: minikube
      - kubeContext: docker-desktop
      - kubeContext: kind-predator
    build:
      local:
        push: false
    deploy:
      kubectl:
        manifests:
          - k8s/namespace.yaml
          - k8s/configmaps.yaml
          - k8s/secrets.yaml
          - k8s/storage.yaml
          - k8s/postgres.yaml
          - k8s/redis.yaml
          - k8s/backend.yaml
          - k8s/frontend.yaml
    patches:
      - op: replace
        path: /deploy/kubectl/manifests
        value:
          - k8s/namespace.yaml
          - k8s/configmaps.yaml
          - k8s/secrets.yaml

  - name: production
    build:
      local:
        push: true
      tagPolicy:
        sha256: {}
    deploy:
      kubectl:
        manifests:
          - k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: backend
    namespace: predator-analytics
    port: 8000
    localPort: 8000
  - resourceType: service
    resourceName: frontend
    namespace: predator-analytics
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: grafana
    namespace: predator-analytics
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: opensearch-dashboards
    namespace: predator-analytics
    port: 5601
    localPort: 5601
