import httpx
from typing import AsyncGenerator

class AutoGeneratedHarvester_courts_law:
    def __init__(self):
        self.base_url = "https://reyestr.court.gov.ua/"
        self.metadata = {
            'id': 'courts_law',
            'name': 'Суди та законодавство',
            'type': 'web_scrape',
            'url': 'https://reyestr.court.gov.ua/',
            'priority': 'high',
            'tags': ['courts', 'law'],
            'instruction': 'Find court decisions and legislative acts APIs.',
            'category': 'Державні реєстри та суди'
        }

    async def harvest(self) -> AsyncGenerator[dict, None]:
        async with httpx.AsyncClient(follow_redirects=True) as client:
            try:
                response = await client.get(self.base_url)
                response.raise_for_status()
                yield {
                    'url': self.base_url,
                    'status_code': response.status_code,
                    'content': response.text,
                    'metadata': self.metadata
                }
            except httpx.RequestError as e:
                if "[Errno 8]" in str(e):
                    yield {}
                else:
                    yield {}
            except Exception:
                yield {}