import httpx
from typing import AsyncGenerator

class AutoGeneratedHarvester_pep_sanctions:
    def __init__(self):
        self.base_url = "https://pep.org.ua/uk/api/"

    async def harvest(self) -> AsyncGenerator[dict, None]:
        try:
            async with httpx.AsyncClient(follow_redirects=True) as client:
                response = await client.get(self.base_url)
                response.raise_for_status()
                data = response.json()
                yield data
        except httpx.RequestError as e:
            if "[Errno 8]" in str(e):
                return
            raise
        except Exception:
            return