import httpx
from typing import AsyncGenerator, Dict, Any

class AutoGeneratedHarvester_state_registries:
    def __init__(self):
        self.base_url = "https://data.gov.ua/api/3/action/package_search"
        self.headers = {
            "User-Agent": "PREDATOR AI Factory Harvester/1.0"
        }

    async def harvest(self) -> AsyncGenerator[Dict[str, Any], None]:
        async with httpx.AsyncClient(follow_redirects=True) as client:
            try:
                response = await client.get(
                    self.base_url,
                    headers=self.headers,
                    timeout=30.0
                )
                response.raise_for_status()
                data = response.json()
                yield data
            except httpx.RequestError as e:
                if "[Errno 8]" in str(e):
                    return
                raise
            except Exception:
                return