import httpx
from typing import AsyncGenerator, Dict, Any

class AutoGeneratedHarvester_state_registries:
    def __init__(self):
        self.base_url = "https://data.gov.ua/api/3/action/package_search"
        self.params = {
            "q": "Державні реєстри",
            "rows": 100,
            "start": 0
        }

    async def harvest(self) -> AsyncGenerator[Dict[str, Any], None]:
        async with httpx.AsyncClient() as client:
            while True:
                response = await client.get(self.base_url, params=self.params)
                response.raise_for_status()
                data = response.json()

                if not data.get("result", {}).get("results"):
                    break

                for item in data["result"]["results"]:
                    yield item

                self.params["start"] += self.params["rows"]