import httpx
from typing import AsyncGenerator

class AutoGeneratedHarvester_tenders_spending:
    def __init__(self):
        self.base_url = "https://public.api.openprocurement.org/api/2.5/tenders"

    async def harvest(self) -> AsyncGenerator[dict, None]:
        async with httpx.AsyncClient(follow_redirects=True) as client:
            try:
                response = await client.get(self.base_url)
                response.raise_for_status()
                data = response.json()
                yield data
            except httpx.RequestError as e:
                if "[Errno 8]" in str(e):
                    return
                raise
            except Exception:
                return