
import asyncio
import sys
import importlib.util
import os

async def run_test():
    try:
        # Додаємо шлях до директорії ingestion-worker, щоб імпорти app.core працювали
        from pathlib import Path
        ingestion_dir = str(Path("/Users/Shared/Predator_60/services/ingestion-worker/app/harvesters/autogen/tenders_spending_harvester.py").resolve().parent.parent.parent.parent)
        sys.path.insert(0, ingestion_dir)
        
        spec = importlib.util.spec_from_file_location("harvester", "/Users/Shared/Predator_60/services/ingestion-worker/app/harvesters/autogen/tenders_spending_harvester.py")
        harvester_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(harvester_module)
        
        # Знаходимо клас Harvester (будь-який клас що починається з AutoGenerated)
        harvester_class = None
        for name in dir(harvester_module):
            if name.startswith("AutoGenerated"):
                harvester_class = getattr(harvester_module, name)
                break
                
        if not harvester_class:
            print("ERROR: Harvester class not found")
            sys.exit(1)

        try:
            instance = harvester_class(config={})
        except TypeError:
            instance = harvester_class()
        
        count = 0
        async for item in instance.harvest():
            print(f"Sample item: {item}")
            count += 1
            if count >= 3: # Тестуємо тільки 3 записи
                break
        print("SUCCESS: Connector executed without crashing")
        sys.exit(0)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

if __name__ == "__main__":
    asyncio.run(run_test())
