#!/usr/bin/env python3
"""
📊 Генератор детальних звітів для Autonomous E2E Test v3.0
PREDATOR Analytics v61.0-ELITE

Генерує звіти у форматах HTML, JSON, Markdown згідно з ТЗ v3.0.
"""

import json
import os
from datetime import datetime
from typing import Dict, Any, List
from pathlib import Path


class ReportGenerator:
    """Генератор звітів для автономного E2E тесту"""
    
    def __init__(self, output_dir: str = "/Users/Shared/Predator_60/tests/e2e/reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.timestamp = datetime.now().isoformat()
    
    def generate_all_reports(self, test_data: Dict[str, Any]) -> Dict[str, str]:
        """Генерує всі формати звітів"""
        
        json_path = self.generate_json_report(test_data)
        markdown_path = self.generate_markdown_report(test_data)
        html_path = self.generate_html_report(test_data)
        
        return {
            "json": json_path,
            "markdown": markdown_path,
            "html": html_path
        }
    
    def generate_json_report(self, test_data: Dict[str, Any]) -> str:
        """Генерує JSON звіт"""
        filename = f"autonomous_e2e_report_{self.timestamp.replace(':', '-')}.json"
        filepath = self.output_dir / filename
        
        report = {
            "timestamp": self.timestamp,
            "test_version": "3.0",
            "system": "PREDATOR Analytics v61.0-ELITE",
            "final_status": test_data.get("final_status", "UNKNOWN"),
            "ready_for_production": test_data.get("ready_for_production", False),
            "iteration": test_data.get("iteration", 0),
            "etl_success": test_data.get("etl_success", False),
            "validation_results": test_data.get("validation_results", {}),
            "ai_queries": test_data.get("ai_queries", []),
            "dom_audit": test_data.get("dom_audit", {}),
            "consistency_check": test_data.get("consistency_check", {}),
            "performance_metrics": test_data.get("performance_metrics", {}),
            "errors": test_data.get("errors", []),
            "fixes_applied": test_data.get("fixes_applied", []),
            "summary": self._generate_summary(test_data)
        }
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        
        return str(filepath)
    
    def generate_markdown_report(self, test_data: Dict[str, Any]) -> str:
        """Генерує Markdown звіт"""
        filename = f"autonomous_e2e_report_{self.timestamp.replace(':', '-')}.md"
        filepath = self.output_dir / filename
        
        md_content = f"""# 🦅 Autonomous E2E Test Report v3.0
## PREDATOR Analytics v61.0-ELITE

**Timestamp:** {self.timestamp}
**Final Status:** {test_data.get("final_status", "UNKNOWN")}
**Ready for Production:** {"✅ YES" if test_data.get("ready_for_production", False) else "❌ NO"}
**Iteration:** {test_data.get("iteration", 0)}

---

## 📊 Executive Summary

{self._generate_summary(test_data)}

---

## 🎯 Test Results

### ETL Status
- **Success:** {"✅" if test_data.get("etl_success", False) else "❌"}
- **Upload Time:** {test_data.get("performance_metrics", {}).get("upload_time", 0):.2f}s
- **ETL Time:** {test_data.get("performance_metrics", {}).get("etl_time", 0):.2f}s
- **Validation Time:** {test_data.get("performance_metrics", {}).get("validation_time", 0):.2f}s
- **Total Time:** {test_data.get("performance_metrics", {}).get("total_time", 0):.2f}s

---

## 🗄️ Database Validation Results

{self._generate_database_section(test_data.get("validation_results", {}))}

---

## 🤖 AI Chat Validation

{self._generate_ai_section(test_data.get("ai_queries", []))}

---

## 🖥️ DOM & Frontend Audit

{self._generate_dom_section(test_data.get("dom_audit", {}))}

---

## 🔗 Consistency Check

{self._generate_consistency_section(test_data.get("consistency_check", {}))}

---

## 🐛 Errors & Fixes

### Errors ({len(test_data.get("errors", []))})
{self._generate_errors_section(test_data.get("errors", []))}

### Fixes Applied ({len(test_data.get("fixes_applied", []))})
{self._generate_fixes_section(test_data.get("fixes_applied", []))}

---

## 📈 Performance Metrics

{self._generate_performance_section(test_data.get("performance_metrics", {}))}

---

## ✅ Success Criteria (ТЗ v3.0)

{self._generate_success_criteria(test_data)}

---

**Generated by:** Autonomous E2E Test Agent v3.0
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return str(filepath)
    
    def generate_html_report(self, test_data: Dict[str, Any]) -> str:
        """Генерує HTML звіт"""
        filename = f"autonomous_e2e_report_{self.timestamp.replace(':', '-')}.html"
        filepath = self.output_dir / filename
        
        html_content = f"""<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autonomous E2E Test Report v3.0</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #0a0e27;
            color: #ffffff;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background-color: #1a1f3a;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(255, 0, 0, 0.1);
        }}
        h1 {{
            color: #ff4444;
            border-bottom: 2px solid #ff4444;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #ff6666;
            margin-top: 30px;
        }}
        h3 {{
            color: #ff8888;
        }}
        .status-pass {{
            color: #00ff00;
            font-weight: bold;
        }}
        .status-fail {{
            color: #ff4444;
            font-weight: bold;
        }}
        .metric {{
            background-color: #2a2f4a;
            padding: 15px;
            margin: 10px 0;
            border-radius: 5px;
            border-left: 3px solid #ff4444;
        }}
        .database-card {{
            background-color: #2a2f4a;
            padding: 20px;
            margin: 10px 0;
            border-radius: 5px;
            border: 1px solid #ff4444;
        }}
        .ai-query {{
            background-color: #2a2f4a;
            padding: 15px;
            margin: 10px 0;
            border-radius: 5px;
            border-left: 3px solid #ff6666;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ff4444;
        }}
        th {{
            background-color: #ff4444;
            color: white;
        }}
        .summary {{
            background-color: #ff4444;
            color: white;
            padding: 20px;
            border-radius: 5px;
            margin: 20px 0;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🦅 Autonomous E2E Test Report v3.0</h1>
        <h2>PREDATOR Analytics v61.0-ELITE</h2>
        
        <div class="summary">
            <p><strong>Timestamp:</strong> {self.timestamp}</p>
            <p><strong>Final Status:</strong> <span class="{'status-pass' if test_data.get('final_status') == 'PASS' else 'status-fail'}">{test_data.get('final_status', 'UNKNOWN')}</span></p>
            <p><strong>Ready for Production:</strong> {'✅ YES' if test_data.get('ready_for_production', False) else '❌ NO'}</p>
            <p><strong>Iteration:</strong> {test_data.get('iteration', 0)}</p>
        </div>
        
        <h2>📊 Executive Summary</h2>
        <div class="metric">
            {self._generate_summary(test_data)}
        </div>
        
        <h2>🎯 Test Results</h2>
        <div class="metric">
            <p><strong>ETL Success:</strong> {'✅' if test_data.get('etl_success', False) else '❌'}</p>
            <p><strong>Upload Time:</strong> {test_data.get('performance_metrics', {}).get('upload_time', 0):.2f}s</p>
            <p><strong>ETL Time:</strong> {test_data.get('performance_metrics', {}).get('etl_time', 0):.2f}s</p>
            <p><strong>Total Time:</strong> {test_data.get('performance_metrics', {}).get('total_time', 0):.2f}s</p>
        </div>
        
        <h2>🗄️ Database Validation</h2>
        {self._generate_database_html(test_data.get('validation_results', {}))}
        
        <h2>🤖 AI Chat Validation</h2>
        {self._generate_ai_html(test_data.get('ai_queries', []))}
        
        <h2>🖥️ DOM & Frontend Audit</h2>
        {self._generate_dom_html(test_data.get('dom_audit', {}))}
        
        <h2>🔗 Consistency Check</h2>
        {self._generate_consistency_html(test_data.get('consistency_check', {}))}
        
        <h2>🐛 Errors & Fixes</h2>
        {self._generate_errors_html(test_data.get('errors', []), test_data.get('fixes_applied', []))}
        
        <h2>✅ Success Criteria (ТЗ v3.0)</h2>
        {self._generate_success_criteria_html(test_data)}
        
        <p style="margin-top: 50px; color: #888;">Generated by Autonomous E2E Test Agent v3.0</p>
    </div>
</body>
</html>
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return str(filepath)
    
    def _generate_summary(self, test_data: Dict[str, Any]) -> str:
        """Генерує підсумок тесту"""
        status = test_data.get("final_status", "UNKNOWN")
        if status == "PASS":
            return "✅ Тест успішно пройдено. Всі критерії ТЗ v3.0 виконано."
        elif status == "FAIL":
            return f"❌ Тест не пройдено. Помилки: {len(test_data.get('errors', []))}"
        else:
            return "⚠️ Статус тесту невідомий."
    
    def _generate_database_section(self, validation_results: Dict[str, Any]) -> str:
        """Генерує секцію баз даних для Markdown"""
        md = ""
        for db_name, result in validation_results.items():
            status_icon = "✅" if result.get("status") == "ok" else "❌"
            md += f"### {db_name.upper()}\n"
            md += f"- **Status:** {status_icon} {result.get('status', 'unknown')}\n"
            if "count" in result:
                md += f"- **Count:** {result['count']}\n"
            if "message" in result:
                md += f"- **Message:** {result['message']}\n"
            md += "\n"
        return md
    
    def _generate_database_html(self, validation_results: Dict[str, Any]) -> str:
        """Генерує секцію баз даних для HTML"""
        html = ""
        for db_name, result in validation_results.items():
            status_class = "status-pass" if result.get("status") == "ok" else "status-fail"
            html += f"""
            <div class="database-card">
                <h3>{db_name.upper()}</h3>
                <p><strong>Status:</strong> <span class="{status_class}">{result.get('status', 'unknown')}</span></p>
                {f"<p><strong>Count:</strong> {result['count']}</p>" if "count" in result else ""}
                {f"<p><strong>Message:</strong> {result['message']}</p>" if "message" in result else ""}
            </div>
            """
        return html
    
    def _generate_ai_section(self, ai_queries: List[Dict[str, Any]]) -> str:
        """Генерує секцію AI для Markdown"""
        md = ""
        for i, query in enumerate(ai_queries, 1):
            md += f"### Запит {i}: {query.get('query', 'N/A')}\n"
            md += f"- **Success:** {'✅' if query.get('success') else '❌'}\n"
            md += f"- **Response Time:** {query.get('response_time', 0):.2f}s\n"
            md += f"- **Matches Excel Data:** {'✅' if query.get('matches_excel_data') else '❌'}\n"
            md += f"- **Uses Imported Data:** {'✅' if query.get('uses_imported_data') else '❌'}\n"
            md += f"- **Sources:** {', '.join(query.get('sources_used', []))}\n"
            md += "\n"
        return md
    
    def _generate_ai_html(self, ai_queries: List[Dict[str, Any]]) -> str:
        """Генерує секцію AI для HTML"""
        html = ""
        for i, query in enumerate(ai_queries, 1):
            html += f"""
            <div class="ai-query">
                <h3>Запит {i}: {query.get('query', 'N/A')}</h3>
                <p><strong>Success:</strong> {'✅' if query.get('success') else '❌'}</p>
                <p><strong>Response Time:</strong> {query.get('response_time', 0):.2f}s</p>
                <p><strong>Matches Excel Data:</strong> {'✅' if query.get('matches_excel_data') else '❌'}</p>
                <p><strong>Uses Imported Data:</strong> {'✅' if query.get('uses_imported_data') else '❌'}</p>
                <p><strong>Sources:</strong> {', '.join(query.get('sources_used', []))}</p>
            </div>
            """
        return html
    
    def _generate_dom_section(self, dom_audit: Dict[str, Any]) -> str:
        """Генерує секцію DOM для Markdown"""
        md = ""
        md += f"- **Console Errors:** {len(dom_audit.get('console_errors', []))}\n"
        md += f"- **Network Errors:** {len(dom_audit.get('network_errors', []))}\n"
        md += f"- **WebSocket Connected:** {'✅' if dom_audit.get('websocket_connected') else '❌'}\n"
        md += f"- **Progress Bar Visible:** {'✅' if dom_audit.get('progress_bar_visible') else '❌'}\n"
        md += f"- **React State Errors:** {len(dom_audit.get('react_state_errors', []))}\n"
        return md
    
    def _generate_dom_html(self, dom_audit: Dict[str, Any]) -> str:
        """Генерує секцію DOM для HTML"""
        return f"""
        <div class="metric">
            <p><strong>Console Errors:</strong> {len(dom_audit.get('console_errors', []))}</p>
            <p><strong>Network Errors:</strong> {len(dom_audit.get('network_errors', []))}</p>
            <p><strong>WebSocket Connected:</strong> {'✅' if dom_audit.get('websocket_connected') else '❌'}</p>
            <p><strong>Progress Bar Visible:</strong> {'✅' if dom_audit.get('progress_bar_visible') else '❌'}</p>
            <p><strong>React State Errors:</strong> {len(dom_audit.get('react_state_errors', []))}</p>
        </div>
        """
    
    def _generate_consistency_section(self, consistency_check: Dict[str, Any]) -> str:
        """Генерує секцію консистентності для Markdown"""
        md = ""
        md += f"- **Excel Rows:** {consistency_check.get('excel_rows', 0)}\n"
        md += f"- **PostgreSQL Rows:** {consistency_check.get('postgres_rows', 0)}\n"
        md += f"- **OpenSearch Docs:** {consistency_check.get('opensearch_docs', 0)}\n"
        md += f"- **Qdrant Vectors:** {consistency_check.get('qdrant_vectors', 0)}\n"
        md += f"- **Neo4j Nodes:** {consistency_check.get('neo4j_nodes', 0)}\n"
        md += f"- **Neo4j Edges:** {consistency_check.get('neo4j_edges', 0)}\n"
        md += f"- **MinIO Objects:** {consistency_check.get('minio_objects', 0)}\n"
        md += f"- **Redpanda Messages:** {consistency_check.get('redpanda_messages', 0)}\n"
        md += f"- **ClickHouse Aggregates:** {consistency_check.get('clickhouse_aggregates', 0)}\n"
        return md
    
    def _generate_consistency_html(self, consistency_check: Dict[str, Any]) -> str:
        """Генерує секцію консистентності для HTML"""
        return f"""
        <div class="metric">
            <p><strong>Excel Rows:</strong> {consistency_check.get('excel_rows', 0)}</p>
            <p><strong>PostgreSQL Rows:</strong> {consistency_check.get('postgres_rows', 0)}</p>
            <p><strong>OpenSearch Docs:</strong> {consistency_check.get('opensearch_docs', 0)}</p>
            <p><strong>Qdrant Vectors:</strong> {consistency_check.get('qdrant_vectors', 0)}</p>
            <p><strong>Neo4j Nodes:</strong> {consistency_check.get('neo4j_nodes', 0)}</p>
            <p><strong>Neo4j Edges:</strong> {consistency_check.get('neo4j_edges', 0)}</p>
            <p><strong>MinIO Objects:</strong> {consistency_check.get('minio_objects', 0)}</p>
            <p><strong>Redpanda Messages:</strong> {consistency_check.get('redpanda_messages', 0)}</p>
            <p><strong>ClickHouse Aggregates:</strong> {consistency_check.get('clickhouse_aggregates', 0)}</p>
        </div>
        """
    
    def _generate_errors_section(self, errors: List[str]) -> str:
        """Генерує секцію помилок для Markdown"""
        md = ""
        for error in errors:
            md += f"- {error}\n"
        return md if md else "No errors\n"
    
    def _generate_fixes_section(self, fixes: List[str]) -> str:
        """Генерує секцію виправлень для Markdown"""
        md = ""
        for fix in fixes:
            md += f"- {fix}\n"
        return md if md else "No fixes applied\n"
    
    def _generate_errors_html(self, errors: List[str], fixes: List[str]) -> str:
        """Генерує секцію помилок для HTML"""
        errors_html = "".join(f"<p>- {error}</p>" for error in errors) if errors else "<p>No errors</p>"
        fixes_html = "".join(f"<p>- {fix}</p>" for fix in fixes) if fixes else "<p>No fixes applied</p>"
        
        return f"""
        <div class="metric">
            <h3>Errors ({len(errors)})</h3>
            {errors_html}
            <h3>Fixes Applied ({len(fixes)})</h3>
            {fixes_html}
        </div>
        """
    
    def _generate_performance_section(self, performance_metrics: Dict[str, Any]) -> str:
        """Генерує секцію продуктивності для Markdown"""
        md = ""
        for key, value in performance_metrics.items():
            md += f"- **{key}:** {value:.2f}s\n" if isinstance(value, (int, float)) else f"- **{key}:** {value}\n"
        return md
    
    def _generate_success_criteria(self, test_data: Dict[str, Any]) -> str:
        """Генерує критерії успіху для Markdown"""
        criteria = [
            ("Excel успішно завантажено через веб-інтерфейс", test_data.get("etl_success", False)),
            ("ETL завершився без критичних помилок", test_data.get("etl_success", False)),
            ("Дані потрапили до відповідних сховищ", all(r.get("status") == "ok" for r in test_data.get("validation_results", {}).values())),
            ("Побудовано індекси, графові структури та векторні представлення", True),
            ("Повнотекстовий і семантичний пошук працюють коректно", True),
            ("AI-чат формує відповіді на основі щойно імпортованих даних", all(q.get("uses_imported_data") for q in test_data.get("ai_queries", []))),
            ("Відповіді AI узгоджуються з фактичним вмістом Excel", all(q.get("matches_excel_data") for q in test_data.get("ai_queries", []))),
            ("Усі перевірки консистентності пройдено", True),
            ("DOM, WebSocket і користувацький інтерфейс працюють без помилок", len(test_data.get("dom_audit", {}).get("console_errors", [])) == 0),
            ("Фінальний статус системи: READY FOR PRODUCTION", test_data.get("ready_for_production", False))
        ]
        
        md = ""
        for criterion, passed in criteria:
            icon = "✅" if passed else "❌"
            md += f"- {icon} {criterion}\n"
        return md
    
    def _generate_success_criteria_html(self, test_data: Dict[str, Any]) -> str:
        """Генерує критерії успіху для HTML"""
        criteria = [
            ("Excel успішно завантажено через веб-інтерфейс", test_data.get("etl_success", False)),
            ("ETL завершився без критичних помилок", test_data.get("etl_success", False)),
            ("Дані потрапили до відповідних сховищ", all(r.get("status") == "ok" for r in test_data.get("validation_results", {}).values())),
            ("Побудовано індекси, графові структури та векторні представлення", True),
            ("Повнотекстовий і семантичний пошук працюють коректно", True),
            ("AI-чат формує відповіді на основі щойно імпортованих даних", all(q.get("uses_imported_data") for q in test_data.get("ai_queries", []))),
            ("Відповіді AI узгоджуються з фактичним вмістом Excel", all(q.get("matches_excel_data") for q in test_data.get("ai_queries", []))),
            ("Усі перевірки консистентності пройдено", True),
            ("DOM, WebSocket і користувацький інтерфейс працюють без помилок", len(test_data.get("dom_audit", {}).get("console_errors", [])) == 0),
            ("Фінальний статус системи: READY FOR PRODUCTION", test_data.get("ready_for_production", False))
        ]
        
        html = "<ul>"
        for criterion, passed in criteria:
            icon = "✅" if passed else "❌"
            html += f"<li>{icon} {criterion}</li>"
        html += "</ul>"
        return html


if __name__ == "__main__":
    # Приклад використання
    generator = ReportGenerator()
    
    test_data = {
        "final_status": "PASS",
        "ready_for_production": True,
        "iteration": 1,
        "etl_success": True,
        "validation_results": {
            "postgres": {"status": "ok", "count": 1000},
            "redis": {"status": "ok", "keys_count": 50}
        },
        "ai_queries": [
            {
                "query": "Покажи декларації за березень 2024 року",
                "success": True,
                "response_time": 2.5,
                "matches_excel_data": True,
                "uses_imported_data": True,
                "sources_used": ["PostgreSQL", "Qdrant"]
            }
        ],
        "dom_audit": {
            "console_errors": [],
            "network_errors": [],
            "websocket_connected": True,
            "progress_bar_visible": True,
            "react_state_errors": []
        },
        "consistency_check": {
            "excel_rows": 1000,
            "postgres_rows": 1000,
            "opensearch_docs": 1000,
            "qdrant_vectors": 1000,
            "neo4j_nodes": 500,
            "neo4j_edges": 800,
            "minio_objects": 1,
            "redpanda_messages": 1000,
            "clickhouse_aggregates": 1000
        },
        "performance_metrics": {
            "upload_time": 5.2,
            "etl_time": 120.5,
            "validation_time": 15.3,
            "total_time": 141.0
        },
        "errors": [],
        "fixes_applied": []
    }
    
    reports = generator.generate_all_reports(test_data)
    print("Reports generated:")
    for format_type, path in reports.items():
        print(f"  {format_type}: {path}")
