apiVersion: v2
name: predator
description: PREDATOR Analytics v58.2 WRAITH Full Stack Chart
type: application
version: 58.2.0
appVersion: "58.2-WRAITH"

dependencies:
  - name: postgresql
    version: 15.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: neo4j
    version: 5.21.0
    repository: https://helm.neo4j.com/neo4j
    condition: neo4j.enabled

