apiVersion: v2
name: predator
description: PREDATOR Analytics v55.1 Ironclad Full Stack Chart
type: application
version: 55.1.0
appVersion: "55.1.0"
dependencies:
  - name: postgresql
    version: 15.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: neo4j
    version: 5.21.0
    repository: https://helm.neo4j.com/neo4j
    condition: neo4j.enabled
