apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "predator-analytics.fullname" . }}-mlflow
  labels:
    {{- include "predator-analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mlflow.persistence.size }}
