class AutoGeneratedPipeline_Державніреєстри:
    async def run(self):
        harvester = Harvester()
        normalizer = Normalizer()

        raw_data = await harvester.extract()
        normalized_data = await normalizer.transform(raw_data)

        return normalized_data