# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_communication_pb2 as agent__communication__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_communication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArbiterServiceStub(object):
    """Service for Constitutional Governance (Arbiter)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAuthorization = channel.unary_unary(
                '/predator.swarm.v1.ArbiterService/CheckAuthorization',
                request_serializer=agent__communication__pb2.AuthorizationRequest.SerializeToString,
                response_deserializer=agent__communication__pb2.AuthorizationResponse.FromString,
                _registered_method=True)
        self.ReportAction = channel.unary_unary(
                '/predator.swarm.v1.ArbiterService/ReportAction',
                request_serializer=agent__communication__pb2.ActionLog.SerializeToString,
                response_deserializer=agent__communication__pb2.ActionResponse.FromString,
                _registered_method=True)


class ArbiterServiceServicer(object):
    """Service for Constitutional Governance (Arbiter)
    """

    def CheckAuthorization(self, request, context):
        """Check if an action is constitutionally allowed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportAction(self, request, context):
        """Log an action to the Truth Ledger
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArbiterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAuthorization,
                    request_deserializer=agent__communication__pb2.AuthorizationRequest.FromString,
                    response_serializer=agent__communication__pb2.AuthorizationResponse.SerializeToString,
            ),
            'ReportAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAction,
                    request_deserializer=agent__communication__pb2.ActionLog.FromString,
                    response_serializer=agent__communication__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'predator.swarm.v1.ArbiterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('predator.swarm.v1.ArbiterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArbiterService(object):
    """Service for Constitutional Governance (Arbiter)
    """

    @staticmethod
    def CheckAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/predator.swarm.v1.ArbiterService/CheckAuthorization',
            agent__communication__pb2.AuthorizationRequest.SerializeToString,
            agent__communication__pb2.AuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/predator.swarm.v1.ArbiterService/ReportAction',
            agent__communication__pb2.ActionLog.SerializeToString,
            agent__communication__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SwarmServiceStub(object):
    """Service for Inter-Agent Swarm Communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastEvent = channel.unary_unary(
                '/predator.swarm.v1.SwarmService/BroadcastEvent',
                request_serializer=agent__communication__pb2.SwarmEvent.SerializeToString,
                response_deserializer=agent__communication__pb2.SwarmAck.FromString,
                _registered_method=True)
        self.ProposeAction = channel.unary_unary(
                '/predator.swarm.v1.SwarmService/ProposeAction',
                request_serializer=agent__communication__pb2.Proposal.SerializeToString,
                response_deserializer=agent__communication__pb2.ConsensusResponse.FromString,
                _registered_method=True)


class SwarmServiceServicer(object):
    """Service for Inter-Agent Swarm Communication
    """

    def BroadcastEvent(self, request, context):
        """Broadcast an event to the swarm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeAction(self, request, context):
        """Propose a change for swarm consensus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwarmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastEvent,
                    request_deserializer=agent__communication__pb2.SwarmEvent.FromString,
                    response_serializer=agent__communication__pb2.SwarmAck.SerializeToString,
            ),
            'ProposeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeAction,
                    request_deserializer=agent__communication__pb2.Proposal.FromString,
                    response_serializer=agent__communication__pb2.ConsensusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'predator.swarm.v1.SwarmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('predator.swarm.v1.SwarmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SwarmService(object):
    """Service for Inter-Agent Swarm Communication
    """

    @staticmethod
    def BroadcastEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/predator.swarm.v1.SwarmService/BroadcastEvent',
            agent__communication__pb2.SwarmEvent.SerializeToString,
            agent__communication__pb2.SwarmAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/predator.swarm.v1.SwarmService/ProposeAction',
            agent__communication__pb2.Proposal.SerializeToString,
            agent__communication__pb2.ConsensusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
