const React = require('react');

const MockComponent = (props) => {
  return React.createElement('div', {
    'data-mock': 'true',
    style: { display: 'none' },
    ...props
  }, props.children);
};

const IconMock = (props) => {
  return React.createElement('svg', {
    width: 24,
    height: 24,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: 2,
    'data-mock-icon': 'true',
    ...props
  });
};

const mocks = {
  // Navigation / Router
  BrowserRouter: MockComponent,
  Routes: MockComponent,
  Route: MockComponent,
  Link: MockComponent,
  NavLink: MockComponent,
  Navigate: MockComponent,
  useNavigate: () => (() => {}),
  useLocation: () => ({ pathname: '/' }),
  useParams: () => ({}),

  // Framer Motion
  motion: new Proxy({}, {
    get: () => MockComponent
  }),
  AnimatePresence: MockComponent,

  // Three / Fiber / Drei
  Canvas: MockComponent,
  useFrame: () => {},
  useThree: () => ({ camera: {}, scene: {}, gl: { domElement: {} } }),
  useLoader: () => {},
  extend: () => {},
  OrbitControls: MockComponent,
  PerspectiveCamera: MockComponent,
  Stars: MockComponent,
  Text: MockComponent,
  Grid: MockComponent,
  Plane: MockComponent,
  Sphere: MockComponent,
  Box: MockComponent,
  Float: MockComponent,
  Html: MockComponent,
  MeshDistortMaterial: MockComponent,
  MeshTransmissionMaterial: MockComponent,
  QuadraticBezierLine: MockComponent,
  CameraControls: MockComponent,
  ContactShadows: MockComponent,
  Environment: MockComponent,

  // Recharts
  ResponsiveContainer: MockComponent,
  AreaChart: MockComponent,
  BarChart: MockComponent,
  LineChart: MockComponent,
  Area: MockComponent,
  Bar: MockComponent,
  Line: MockComponent,
  XAxis: MockComponent,
  YAxis: MockComponent,
  CartesianGrid: MockComponent,
  Tooltip: MockComponent,
  Legend: MockComponent,

  // EXPLICIT LUCIDE ICONS (from your list)
  Activity: IconMock,
  AlertCircle: IconMock,
  AlertOctagon: IconMock,
  AlertTriangle: IconMock,
  Archive: IconMock,
  ArrowDown: IconMock,
  ArrowLeft: IconMock,
  ArrowRight: IconMock,
  ArrowRightLeft: IconMock,
  ArrowUp: IconMock,
  ArrowUpRight: IconMock,
  Award: IconMock,
  BarChart2: IconMock,
  BarChart3: IconMock,
  Bell: IconMock,
  Binary: IconMock,
  Bookmark: IconMock,
  Bot: IconMock,
  Box: IconMock,
  Brain: IconMock,
  BrainCircuit: IconMock,
  Briefcase: IconMock,
  Bug: IconMock,
  Building: IconMock,
  Building2: IconMock,
  Calculator: IconMock,
  Calendar: IconMock,
  Check: IconMock,
  CheckCircle: IconMock,
  CheckCircle2: IconMock,
  ChevronDown: IconMock,
  ChevronRight: IconMock,
  ChevronUp: IconMock,
  Circle: IconMock,
  Clock: IconMock,
  Cloud: IconMock,
  Code: IconMock,
  Code2: IconMock,
  Command: IconMock,
  Compass: IconMock,
  Construction: IconMock,
  Cpu: IconMock,
  CreditCard: IconMock,
  Crosshair: IconMock,
  Crown: IconMock,
  Database: IconMock,
  DatabaseIcon: IconMock,
  Dna: IconMock,
  DollarSign: IconMock,
  Download: IconMock,
  ExternalLink: IconMock,
  Eye: IconMock,
  EyeOff: IconMock,
  FileSearch: IconMock,
  FileText: IconMock,
  FileX: IconMock,
  Filter: IconMock,
  Fingerprint: IconMock,
  Gavel: IconMock,
  GitBranch: IconMock,
  GitCommit: IconMock,
  GitMerge: IconMock,
  Globe: IconMock,
  Hammer: IconMock,
  HardDrive: IconMock,
  HelpCircle: IconMock,
  History: IconMock,
  Home: IconMock,
  Inbox: IconMock,
  Info: IconMock,
  Key: IconMock,
  Layers: IconMock,
  Layout: IconMock,
  LayoutGrid: IconMock,
  Leaf: IconMock,
  Lightbulb: IconMock,
  LineChart: IconMock,
  Link: IconMock,
  Loader: IconMock,
  Loader2: IconMock,
  Lock: IconMock,
  LucideIcon: IconMock,
  Mail: IconMock,
  Map: IconMock,
  MapPin: IconMock,
  Maximize2: IconMock,
  Menu: IconMock,
  MessageSquare: IconMock,
  Mic: IconMock,
  MicOff: IconMock,
  Microscope: IconMock,
  Minimize2: IconMock,
  Minus: IconMock,
  Monitor: IconMock,
  MonitorPlay: IconMock,
  Moon: IconMock,
  MoreHorizontal: IconMock,
  Network: IconMock,
  Newspaper: IconMock,
  Package: IconMock,
  Paperclip: IconMock,
  Pause: IconMock,
  Percent: IconMock,
  Phone: IconMock,
  PieChart: IconMock,
  Play: IconMock,
  Plus: IconMock,
  Radio: IconMock,
  RefreshCcw: IconMock,
  RefreshCw: IconMock,
  Rocket: IconMock,
  RotateCcw: IconMock,
  Scan: IconMock,
  ScrollText: IconMock,
  Search: IconMock,
  Send: IconMock,
  Server: IconMock,
  Settings: IconMock,
  Share2: IconMock,
  Shield: IconMock,
  ShieldAlert: IconMock,
  ShieldCheck: IconMock,
  Ship: IconMock,
  Siren: IconMock,
  Smartphone: IconMock,
  Sparkles: IconMock,
  Square: IconMock,
  Star: IconMock,
  Stethoscope: IconMock,
  Sun: IconMock,
  Sword: IconMock,
  Swords: IconMock,
  Table: IconMock,
  Tablet: IconMock,
  Target: IconMock,
  Terminal: IconMock,
  Trash2: IconMock,
  TrendingDown: IconMock,
  TrendingUp: IconMock,
  Trophy: IconMock,
  Truck: IconMock,
  Upload: IconMock,
  User: IconMock,
  UserPlus: IconMock,
  Users: IconMock,
  Volume2: IconMock,
  Wifi: IconMock,
  WifiOff: IconMock,
  X: IconMock,
  XCircle: IconMock,
  Zap: IconMock,
  ZoomIn: IconMock,
  ZoomOut: IconMock
};

module.exports = {
  __esModule: true,
  default: MockComponent,
  ...mocks
};
