model_list:
  # CODING (Gemini Pro Router)
  - model_name: ultra-router-coding
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY"
      api_base: https://generativelanguage.googleapis.com/v1beta
  - model_name: ultra-router-coding
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY_2"
      api_base: https://generativelanguage.googleapis.com/v1beta
  - model_name: ultra-router-coding
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY_3"
      api_base: https://generativelanguage.googleapis.com/v1beta
  - model_name: ultra-router-coding
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY_4"
      api_base: https://generativelanguage.googleapis.com/v1beta
  - model_name: ultra-router-coding
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY_5"
      api_base: https://generativelanguage.googleapis.com/v1beta
  - model_name: ultra-router-coding
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY_6"
      api_base: https://generativelanguage.googleapis.com/v1beta

  # FAST (Gemini Flash)
  - model_name: ultra-router-fast
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY"
      api_base: https://generativelanguage.googleapis.com/v1beta

  # REASONING (Gemini Pro)
  - model_name: ultra-router-reasoning
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: "os.environ/GEMINI_API_KEY_5"
      api_base: https://generativelanguage.googleapis.com/v1beta

litellm_settings:
  routing_strategy: "least-busy"
  num_retries: 5
  request_timeout: 45

general_settings:
  master_key: "sk-antigravity-master-2026"
