import pytest
import os
from unittest.mock import AsyncMock, patch, MagicMock
from app.discovery.factory import ConnectorFactory
import litellm

# Mock liteLLM response
class MockMessage:
    def __init__(self, content):
        self.content = content

class MockChoice:
    def __init__(self, content):
        self.message = MockMessage(content)

class MockResponse:
    def __init__(self, content):
        self.choices = [MockChoice(content)]

@pytest.mark.asyncio
async def test_generate_connector_success():
    factory = ConnectorFactory(model="test-model")
    
    mock_source = {
        "id": "test-api-123",
        "name": "Test API",
        "url": "https://api.test.com/v1",
        "source_type": "REST API"
    }
    
    mock_code = "```python\nimport httpx\nimport logging\n\nclass AutoGeneratedHarvester_TestAPI:\n    async def harvest(self):\n        yield {'test': 'data'}\n```"
    
    with patch("app.discovery.factory.litellm.acompletion", new_callable=AsyncMock) as mock_completion:
        mock_completion.return_value = MockResponse(mock_code)
        
        file_path = await factory.generate_connector(mock_source)
        
        assert file_path is not None
        assert "test_api_123_harvester.py" in file_path
        assert os.path.exists(file_path)
        
        # Verify cleaned code
        with open(file_path, "r", encoding="utf-8") as f:
            saved_code = f.read()
            
        assert "```python" not in saved_code
        assert "import httpx" in saved_code
        assert "class AutoGeneratedHarvester_TestAPI" in saved_code
        
        # Cleanup
        os.remove(file_path)

@pytest.mark.asyncio
async def test_generate_normalizer_success():
    factory = ConnectorFactory(model="test-model")
    mock_source = {"id": "test-api-123", "name": "Test API"}
    mock_code = "```python\nclass AutoGeneratedNormalizer_TestAPI:\n    def normalize(self, raw_data: dict) -> list:\n        return [raw_data]\n```"
    
    with patch("app.discovery.factory.litellm.acompletion", new_callable=AsyncMock) as mock_completion:
        mock_completion.return_value = MockResponse(mock_code)
        file_path = await factory.generate_normalizer(mock_source)
        
        assert file_path is not None
        assert "test_api_123_normalizer.py" in file_path
        assert os.path.exists(file_path)
        os.remove(file_path)

@pytest.mark.asyncio
async def test_generate_pipeline_success():
    factory = ConnectorFactory(model="test-model")
    mock_source = {"id": "test-api-123", "name": "Test API"}
    mock_code = "```python\nclass AutoGeneratedPipeline_TestAPI:\n    async def run(self):\n        pass\n```"
    
    with patch("app.discovery.factory.litellm.acompletion", new_callable=AsyncMock) as mock_completion:
        mock_completion.return_value = MockResponse(mock_code)
        file_path = await factory.generate_pipeline(mock_source)
        
        assert file_path is not None
        assert "test_api_123_pipeline.py" in file_path
        assert os.path.exists(file_path)
        os.remove(file_path)
