[Interface]
PrivateKey = MF1Ch4CU14wzVXmQXKaqlHhvj1RIW2K7a0wO2tgeKW8=
Address = 10.8.0.2/24
# DNS вимкнений щоб не блокувати інтернет на MacBook
# DNS = 1.1.1.1

[Peer]
# NVIDIA (Compute Node) — статична публічна IP: 178.214.200.25
PublicKey = ndVExwlJhh5EqctA/OkcglJCr63DZtl7FHg8Ipl9Wxo=
Endpoint = 178.214.200.25:51820
# Тільки трафік до VPN-мережі йде через тунель (split tunnel)
# 10.8.0.0/24 — VPN-мережа (аймак та сервіси)
# 192.168.0.0/24 — локальна мережа аймака (бази даних, k3s)
AllowedIPs = 10.8.0.0/24, 192.168.0.0/24
# Keepalive — підтримує тунель через NAT/файрвол
PersistentKeepalive = 25
