[Interface]
PrivateKey = oDQ33e6FtyQAudW/gLgga+mRa5OobjsNCIMw0vrNwGY=
Address = 10.8.0.1/24
ListenPort = 51820

# MacBook Pro (Developer Node)
[Peer]
PublicKey = 2iJv6iJTG0W2qMnQwuN9sdOjZyBjj2jl7a1OOYJ6NF0=
AllowedIPs = 10.8.0.2/32
