[Interface]
# NVIDIA Server — WireGuard Server (NEW CONFIG)
# Версія: v60.6-ELITE
# Розгорнути НА СЕРВЕРІ (194.177.1.40) як: sudo wg-quick up /etc/wireguard/wg0.conf
PrivateKey = yCTCmFKL/FKfoC1f8p7Lv2pI77C5Y+h3kV0kc0NsUmA=
Address = 10.9.0.1/24
ListenPort = 51820

# Форвардинг трафіку до локальних сервісів (K3d, Docker)
PostUp   = sysctl -w net.ipv4.ip_forward=1; iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# MacBook Pro (Developer Node)
[Peer]
PublicKey = IGTEzpkVOc+X6vnQYyZHW9nnZWbyuS4yrYFMDwxfFxE=
PresharedKey = HcwbFViYrfhuIAgijdNeEbOp61pQ5+33G3Pud3U6HFE=
AllowedIPs = 10.9.0.2/32
