[Interface]
# NVIDIA Server — WireGuard Server
# Версія: v60.5-ELITE
PrivateKey = AN/EXV8JjGHeLWEJsnk8NYVMh6br0PFWirUE2/ffIXY=
Address = 10.9.0.1/24
ListenPort = 51821

# Форвардинг трафіку для доступу до локальних сервісів K3d (Kubernetes)
PostUp   = sysctl -w net.ipv4.ip_forward=1; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# MacBook Pro (Developer Node)
[Peer]
PublicKey = 2A3SFB5C5W2O9EhtWaEap0iDMQ9s+RgoP1XgeK9jpF4=
AllowedIPs = 10.9.0.2/32
