[Interface]
# MacBook Pro (Developer Node) — Підключення до NVIDIA Server
# Версія: v60.5-ELITE
PrivateKey = WKqruO41TKgQDu4g5J7gHhJ4146n1uxZdJQg7LDSO3o=
Address = 10.9.0.2/24

[Peer]
# NVIDIA Server
PublicKey = SqqTZFqVCMJweSU68yiuquvLjS3S6j9q4KH/ZpyFQ18=
Endpoint = 194.177.1.240:51821
AllowedIPs = 10.9.0.0/24, 172.18.0.0/16
# Keepalive для підтримання зв'язку через NAT/роутери
PersistentKeepalive = 25
