{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cerebro.fullname" . }}
  labels: {{- include "cerebro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "cerebro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "cerebro.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cerebro
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: REDIS_URL
              value: "redis://{{ .Values.global.redis.host }}:{{ .Values.global.redis.port }}/0"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}"
            - name: ENV
              value: "{{ .Values.env.ENV }}"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
