-- ================================================================
-- Database Migration: Augmented Datasets & XAI Tables
-- Version: 006
-- Created: 2025-12-07
-- Purpose: Support Data Augmentation & Explainable AI features from TZ v5.0
-- ================================================================

-- ---------------------------------------------------------------
-- 1. Augmented Datasets Table (for synthetic training data)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS augmented_datasets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    original_id UUID REFERENCES gold.documents(id) ON DELETE SET NULL,
    augmented_content TEXT NOT NULL,
    augmentation_type VARCHAR(50) NOT NULL,  -- 'synonym', 'paraphrase', 'shuffle', 'backtranslation'
    variation_index INT DEFAULT 0,
    title VARCHAR(500),
    category VARCHAR(100),
    quality_score FLOAT,  -- Optional quality assessment
    used_for_training BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_augmented_original ON augmented_datasets(original_id);
CREATE INDEX idx_augmented_type ON augmented_datasets(augmentation_type);
CREATE INDEX idx_augmented_training ON augmented_datasets(used_for_training) WHERE used_for_training = FALSE;

COMMENT ON TABLE augmented_datasets IS 'Synthetic data generated by DataAugmentor for ML training';

-- ---------------------------------------------------------------
-- 2. XAI Explanations Cache (for reusable explanations)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS xai_explanations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    query_hash VARCHAR(64) NOT NULL,  -- MD5/SHA256 of query
    document_id UUID REFERENCES gold.documents(id) ON DELETE CASCADE,
    explanation_type VARCHAR(50) NOT NULL,  -- 'shap', 'lime', 'attention', 'token_overlap'
    explanation_data JSONB NOT NULL,  -- Full explanation payload
    score FLOAT,  -- Relevance score at time of explanation
    created_at TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP,  -- Cache TTL
    UNIQUE(query_hash, document_id, explanation_type)
);

CREATE INDEX idx_xai_query ON xai_explanations(query_hash);
CREATE INDEX idx_xai_expires ON xai_explanations(expires_at) WHERE expires_at IS NOT NULL;

COMMENT ON TABLE xai_explanations IS 'Cached XAI explanations for search results';

-- ---------------------------------------------------------------
-- 3. ML Training Jobs Table (for H2O/AutoML tracking)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ml_training_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_type VARCHAR(50) NOT NULL,  -- 'fine_tune', 'automl', 'augment'
    model_name VARCHAR(200),
    dataset_name VARCHAR(200),
    status VARCHAR(20) DEFAULT 'pending',  -- pending, running, completed, failed
    parameters JSONB,  -- Training hyperparameters
    metrics JSONB,  -- Training results (loss, accuracy, etc.)
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_by UUID REFERENCES users(id),
    error_message TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_ml_jobs_status ON ml_training_jobs(status, created_at DESC);
CREATE INDEX idx_ml_jobs_type ON ml_training_jobs(job_type);

COMMENT ON TABLE ml_training_jobs IS 'Tracks ML training jobs (H2O, AutoML, fine-tuning)';

-- ---------------------------------------------------------------
-- 4. Feature Flags Table (for A/B testing and gradual rollout)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feature_flags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) UNIQUE NOT NULL,  -- 'xai_enabled', 'multimodal_search', 'federated_learning'
    enabled BOOLEAN DEFAULT FALSE,
    rollout_percentage INT DEFAULT 0,  -- 0-100 for gradual rollout
    description TEXT,
    conditions JSONB,  -- e.g., {"plans": ["premium", "enterprise"]}
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Insert default feature flags
INSERT INTO feature_flags (name, enabled, rollout_percentage, description) VALUES
    ('xai_explanations', true, 100, 'Show XAI explanations for search results'),
    ('data_augmentation', true, 100, 'Enable synthetic data generation'),
    ('multimodal_search', false, 0, 'Enable image+text search with CLIP'),
    ('federated_learning', false, 0, 'Enable federated ML training'),
    ('h2o_studio', false, 0, 'Enable H2O LLM Studio integration')
ON CONFLICT (name) DO NOTHING;

COMMENT ON TABLE feature_flags IS 'Feature flags for gradual rollout and A/B testing';

-- ---------------------------------------------------------------
-- 5. Cost Tracking Table (for Kubecost integration)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cost_tracking (
    id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL,
    namespace VARCHAR(100),
    service VARCHAR(100),
    resource_type VARCHAR(50),  -- 'cpu', 'memory', 'gpu', 'storage'
    usage_amount FLOAT,
    cost_usd FLOAT,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_cost_date ON cost_tracking(date DESC);
CREATE INDEX idx_cost_service ON cost_tracking(service, date DESC);

COMMENT ON TABLE cost_tracking IS 'Cost tracking data from Kubecost for budget monitoring';

-- ---------------------------------------------------------------
-- GRANTS
-- ---------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO predator;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO predator;
