apiVersion: v1
kind: Secret
metadata:
  name: bot-env-vars
  namespace: predator-nvidia
type: Opaque
stringData:
  TELEGRAM_TOKEN: "${TELEGRAM_BOT_TOKEN}"
  GEMINI_API_KEY: "${GEMINI_API_KEY}"
  MISTRAL_API_KEY: "${MISTRAL_API_KEY}"
  GITHUB_TOKEN: "${GITHUB_TOKEN}"
