import { Button } from '@/components/ui/button';
import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  Download, 
  Share2, 
  Sparkles,
  ShieldCheck,
  Zap,
  ChevronRight
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import axios from 'axios';
import { motion } from 'framer-motion';

const API_BASE = "/api/v1/omniverse";

export const OmniverseBriefing: React.FC = () => {
  const [report, setReport] = useState<string>('');
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchBrief = async () => {
      try {
        const res = await axios.get(`${API_BASE}/command/briefing`);
        setReport(res.data.report);
        setData(res.data.data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchBrief();
  }, []);

  if (loading) return (
    <div className="h-full flex flex-col items-center justify-center space-y-4">
      <Sparkles className="text-emerald-500 animate-spin w-12 h-12" />
      <p className="text-[10px] font-black text-white/40 uppercase tracking-[0.5em]">Compiling Intelligence Brief...</p>
    </div>
  );

  return (
    <div className="grid grid-cols-12 gap-8 h-full">
      {/* Sidebar Stats */}
      <div className="col-span-3 space-y-6">
        <div className="p-6 bg-emerald-500/10 border border-emerald-500/20 rounded-3xl space-y-4">
          <div className="flex items-center gap-2 text-emerald-500">
            <ShieldCheck size={20} />
            <span className="text-xs font-black uppercase tracking-widest">System Health</span>
          </div>
          <div className="space-y-4">
            <div>
              <p className="text-[10px] text-white/40 font-bold uppercase tracking-widest">Total Datasets</p>
              <p className="text-2xl font-black text-white">{data?.summary?.total_datasets || 0}</p>
            </div>
            <div>
              <p className="text-[10px] text-white/40 font-bold uppercase tracking-widest">Active Alerts</p>
              <p className="text-2xl font-black text-red-500">{data?.summary?.active_alerts || 0}</p>
            </div>
          </div>
        </div>

        <div className="p-6 bg-white/5 border border-white/10 rounded-3xl space-y-4">
           <h4 className="text-[10px] font-black text-white/60 uppercase tracking-widest">Actions Required</h4>
           <div className="space-y-3">
             {['Security Audit', 'Market Verification', 'Cache Flush'].map((act, i) => (
               <div key={i} className="flex items-center justify-between group cursor-pointer">
                 <span className="text-xs text-white/80 group-hover:text-white transition-colors">{act}</span>
                 <ChevronRight size={14} className="text-white/20 group-hover:text-emerald-500 transition-colors" />
               </div>
             ))}
           </div>
        </div>
      </div>

      {/* Main Report */}
      <div className="col-span-9 bg-white/5 border border-white/10 rounded-3xl overflow-hidden flex flex-col shadow-2xl">
        <div className="p-6 border-b border-white/10 flex items-center justify-between bg-slate-900/50">
          <div className="flex items-center gap-3">
            <FileText className="text-blue-400" />
            <h3 className="text-lg font-black text-white uppercase tracking-tighter italic">Intelligence Briefing</h3>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="cyber" className="p-2 hover:bg-white/10 rounded-lg text-white/60 transition-colors">
              <Download size={18} />
            </Button>
            <Button variant="cyber" className="p-2 hover:bg-white/10 rounded-lg text-white/60 transition-colors">
              <Share2 size={18} />
            </Button>
          </div>
        </div>

        <div className="flex-1 overflow-auto p-12 custom-scrollbar bg-[radial-gradient(circle_at_50%_0%,rgba(16,185,129,0.05)_0%,transparent_50%)]">
          <article className="prose prose-invert max-w-none prose-h1:text-4xl prose-h1:font-black prose-h1:italic prose-h1:tracking-tighter prose-h1:uppercase prose-h1:mb-8 prose-p:text-white/70 prose-p:leading-relaxed prose-strong:text-emerald-400">
            <ReactMarkdown>{report}</ReactMarkdown>
          </article>
          
          <div className="mt-12 pt-12 border-t border-white/5 flex items-center justify-between opacity-30">
            <div className="flex items-center gap-2">
              <Zap size={14} />
              <span className="text-[9px] font-mono uppercase tracking-widest">Generated by Sovereign AI v7.0</span>
            </div>
            <span className="text-[9px] font-mono uppercase tracking-widest">PREDATOR_ELITE_ENCRYPTED_STREAM</span>
          </div>
        </div>
      </div>
    </div>
  );
};
