export const factoryApi = {
  executeRun: async (data?: any) => ({ id: "run_1", status: "success" }),
  getRuns: async () => [
    { id: "run_101", source: "NBU API", status: "SUCCESS", duration: "1.2s", timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(), agents: ["Discovery", "Profiler", "Coder", "QA"] },
    { id: "run_102", source: "OpenSanctions", status: "SUCCESS", duration: "3.4s", timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(), agents: ["Discovery", "Profiler"] },
    { id: "run_103", source: "Prozorro Harvester", status: "RUNNING", duration: "0.8s", timestamp: new Date().toISOString(), agents: ["Discovery"] },
    { id: "run_104", source: "YouControl API", status: "FAILED", duration: "5.1s", timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(), agents: ["Discovery", "Profiler", "Coder", "QA"] },
  ],
  getPatterns: async () => [
    {
      id: "pat_1",
      component: "api",
      pattern_type: "performance",
      pattern_description: "Асинхронний збір банківських даних НБУ з автоматичною пагінацією",
      score: 98,
      gold: true,
      timestamp: new Date().toISOString(),
      hash: "abc123hash",
      tags: ["API", "Harvester"],
      source_run_id: "run_101",
    },
    {
      id: "pat_2",
      component: "backend",
      pattern_type: "stability",
      pattern_description: "Виявлення пов'язаних бенефіціарів через граф зв'язків",
      score: 94,
      gold: true,
      timestamp: new Date().toISOString(),
      hash: "def456hash",
      tags: ["Graph", "Neo4j"],
      source_run_id: "run_102",
    },
    {
      id: "pat_3",
      component: "core",
      pattern_type: "stability",
      pattern_description: "Захист від відмови зовнішніх державних реєстрів",
      score: 91,
      gold: false,
      timestamp: new Date().toISOString(),
      hash: "ghi789hash",
      tags: ["Resilience"],
      source_run_id: "run_103",
    },
    {
      id: "pat_4",
      component: "core",
      pattern_type: "security",
      pattern_description: "Ізольована перевірка коду через AST аналізатор",
      score: 96,
      gold: true,
      timestamp: new Date().toISOString(),
      hash: "jkl012hash",
      tags: ["Security", "Testing"],
      source_run_id: "run_104",
    },
  ],
  getMetrics: async () => ({ total_patterns: 14, gold_patterns: 8, avg_score: 95.2, total_runs: 124 }),
  getStats: async () => ({ total_patterns: 14, gold_patterns: 8, avg_score: 95.2, total_runs: 124 }),
  getHealth: async () => ({ status: "healthy", activeModel: "Qwen-2.5-Coder", progress: 100 }),
  getStatus: async () => ({ active: true }),
  getTrainingStatus: async () => ({ status: "COMPLETED", activeModel: "Qwen-2.5-Coder-Predator", progress: 100 }),
  getTrainingStats: async () => [
    { epoch: 1, loss: 0.45, accuracy: 82 },
    { epoch: 2, loss: 0.28, accuracy: 89 },
    { epoch: 3, loss: 0.14, accuracy: 96 },
  ],
  startTraining: async () => ({ status: "STARTED" }),
  stopTraining: async () => ({ status: "STOPPED" }),
  ingest: async (payload: any) => ({ status: "INGESTED", payload }),
  getAntigravityStatus: async () => ({ status: "active" }),
  getAntigravityTasks: async () => [],
  getAntigravityTaskLogs: async () => "",
  cancelAntigravityTask: async () => ({}),
  createAntigravityTask: async () => ({}),
  getAgentLogs: async () => [
    { timestamp: new Date(Date.now() - 5000).toISOString(), agent: "DiscoveryAgent", level: "info", message: "Аналіз структури OpenAPI для джерела Prozorro..." },
    { timestamp: new Date(Date.now() - 4000).toISOString(), agent: "DiscoveryAgent", level: "success", message: "Знайдено 12 ендпоїнтів. Створено схему сутностей." },
    { timestamp: new Date(Date.now() - 3500).toISOString(), agent: "ProfilerAgent", level: "info", message: "Оцінка якості даних. Перевірка наявності пагінації." },
    { timestamp: new Date(Date.now() - 2000).toISOString(), agent: "ProfilerAgent", level: "warning", message: "Виявлено ліміти Rate Limit (100 req/min). Додано Circuit Breaker." },
    { timestamp: new Date(Date.now() - 1000).toISOString(), agent: "CoderAgent", level: "info", message: "Генерація Python клієнта для Harvester Worker..." },
    { timestamp: new Date().toISOString(), agent: "QAAgent", level: "info", message: "Очікування завершення коду для запуску AST тестів у Ghost Runtime." }
  ],
  triggerDiscovery: async (url: string) => ({ status: "QUEUED", url }),
  setSystemMode: async () => ({}),
  triggerChaos: async () => ({}),
};

export const useFactoryApi = () => factoryApi;