export const factoryApi = {
  executeRun: async (data?: any) => ({ id: "run_1", status: "success" }),
  getRuns: async () => [
    { id: "run_101", source: "NBU API", status: "SUCCESS", duration: "1.2s", timestamp: new Date().toISOString() },
    { id: "run_102", source: "OpenSanctions", status: "SUCCESS", duration: "3.4s", timestamp: new Date().toISOString() },
    { id: "run_103", source: "Prozorro Harvester", status: "RUNNING", duration: "0.8s", timestamp: new Date().toISOString() },
  ],
  getPatterns: async () => [
    {
      id: "pat_1",
      component: "ingestion-worker",
      pattern_type: "REST API Harvester",
      pattern_description: "Асинхронний збір банківських даних НБУ з автоматичною пагінацією",
      score: 98,
      gold: true,
      timestamp: new Date().toISOString(),
    },
    {
      id: "pat_2",
      component: "graph-service",
      pattern_type: "Neo4j Multi-Hop Mapper",
      pattern_description: "Виявлення пов'язаних бенефіціарів через граф зв'язків",
      score: 94,
      gold: true,
      timestamp: new Date().toISOString(),
    },
    {
      id: "pat_3",
      component: "core-api",
      pattern_type: "FastAPI Circuit Breaker",
      pattern_description: "Захист від відмови зовнішніх державних реєстрів",
      score: 91,
      gold: false,
      timestamp: new Date().toISOString(),
    },
    {
      id: "pat_4",
      component: "connector-factory",
      pattern_type: "Ghost Runtime Sandbox",
      pattern_description: "Ізольована перевірка коду через AST аналізатор",
      score: 96,
      gold: true,
      timestamp: new Date().toISOString(),
    },
  ],
  getMetrics: async () => ({ total_patterns: 14, gold_patterns: 8, avg_score: 95.2, total_runs: 124 }),
  getStats: async () => ({ total_patterns: 14, gold_patterns: 8, avg_score: 95.2, total_runs: 124 }),
  getHealth: async () => ({ status: "healthy", activeModel: "Qwen-2.5-Coder", progress: 100 }),
  getStatus: async () => ({ active: true }),
  getTrainingStatus: async () => ({ status: "COMPLETED", activeModel: "Qwen-2.5-Coder-Predator", progress: 100 }),
  getTrainingStats: async () => [
    { epoch: 1, loss: 0.45, accuracy: 82 },
    { epoch: 2, loss: 0.28, accuracy: 89 },
    { epoch: 3, loss: 0.14, accuracy: 96 },
  ],
  startTraining: async () => ({ status: "STARTED" }),
  stopTraining: async () => ({ status: "STOPPED" }),
  ingest: async (payload: any) => ({ status: "INGESTED", payload }),
  getAntigravityStatus: async () => ({ status: "active" }),
  getAntigravityTasks: async () => [],
  getAntigravityTaskLogs: async () => "",
  cancelAntigravityTask: async () => ({}),
  createAntigravityTask: async () => ({}),
  setSystemMode: async () => ({}),
  triggerChaos: async () => ({}),
};

export const useFactoryApi = () => factoryApi;