"""
API Discovery Engine — PREDATOR Analytics
Оркеструє процес Autonomous Discovery Layer:
Crawler -> Evaluator -> Factory -> Sandbox.
"""
import asyncio
import logging
from typing import Optional

from app.discovery.crawler import InternetCrawler, DirectoryScanner
from app.discovery.evaluator import SourceEvaluator
from app.discovery.factory import ConnectorFactory
from app.discovery.sandbox import GhostRuntime

logger = logging.getLogger(__name__)

class APIDiscoveryEngine:
    def __init__(self, neo4j_uri: str, neo4j_user: str, neo4j_password: str):
        logger.info("Initializing API Discovery Engine")
        self.crawler = InternetCrawler()
        self.scanner = DirectoryScanner(self.crawler)
        self.evaluator = SourceEvaluator(neo4j_uri, neo4j_user, neo4j_password)
        self.factory = ConnectorFactory()
        self.sandbox = GhostRuntime()
        self.is_running = False

    async def scan_source(self, url: str) -> dict:
        """TODO: Implement actual LLM-based API schema extraction."""
        logger.warning("scan_source is currently a mock. Need to implement LLM extraction.")
        return {
            "source_url": url,
            "has_openapi": True,
            "has_bulk_dump": False,
            "auth_type": "Bearer",
            "pagination": "cursor",
            "rate_limit_per_min": 60
        }

    async def generate_client(self, metadata: dict) -> str:
        """TODO: Implement actual LiteLLM client generation."""
        logger.warning("generate_client is currently a mock. Need to implement LiteLLM generation.")
        return "class AutoGeneratedClient: pass"

    async def _process_discovered_source(self, source_metadata: dict):
        """Пайплайн для одного знайденого джерела."""
        logger.info(f"Processing discovered source: {source_metadata.get('name')}")
        
        # 1. Оцінка пріоритету
        priority = self.evaluator.evaluate_priority(source_metadata)
        
        # 2. Збереження в Meta-Graph
        await self.evaluator.save_to_metagraph(source_metadata, priority)
        
        # Якщо пріоритет високий, запускаємо Фабрику
        if priority >= 50:
            logger.info(f"Source {source_metadata.get('name')} priority {priority} >= 50. Triggering Factory.")
            
            # 3. Генерація конектора (Harvester)
            script_path = await self.factory.generate_connector(source_metadata)
            
            if script_path:
                # 4. Тестування у Ghost Runtime
                success, logs = await self.sandbox.test_connector(script_path)
                
                if success:
                    logger.info(f"Connector for {source_metadata.get('name')} successfully validated in Ghost Runtime.")
                    
                    # 5. Генерація Нормалізатора
                    normalizer_path = await self.factory.generate_normalizer(source_metadata)
                    if normalizer_path:
                        # 6. Генерація Pipeline
                        pipeline_path = await self.factory.generate_pipeline(source_metadata)
                        if pipeline_path:
                            logger.info(f"Full ETL Pipeline for {source_metadata.get('name')} successfully generated.")
                            # Тут можна публікувати подію в Kafka про створення повного ETL
                else:
                    logger.warning(f"Connector for {source_metadata.get('name')} failed validation. Logs: {logs}")
        else:
            logger.info(f"Source {source_metadata.get('name')} priority {priority} < 50. Ignored for now.")

    async def start_autonomous_loop(self):
        """Глобальний фоновий цикл сканування (Level 4 Autonomy)."""
        self.is_running = True
        logger.info("Autonomous Discovery Loop started.")
        
        backoff_seconds = 60
        
        while self.is_running:
            try:
                logger.info("Starting new discovery cycle...")
                
                # 1. Скануємо APIs.guru
                async for source in self.scanner.scan_apis_guru():
                    await self._process_discovered_source(source)
                    
                # 2. Скануємо CKAN (data.gov.ua)
                async for source in self.scanner.scan_ckan("https://data.gov.ua"):
                    await self._process_discovered_source(source)
                    
                # 3. Скануємо OSINT (OpenSanctions, CISA KEV)
                async for source in self.scanner.scan_osint_sources():
                    await self._process_discovered_source(source)
                    
                # Скидаємо backoff після успішного циклу
                backoff_seconds = 60
                    
            except Exception as e:
                logger.error(f"Error in Autonomous Discovery Loop: {e}")
                logger.info(f"Retrying in {backoff_seconds} seconds due to error...")
                await asyncio.sleep(backoff_seconds)
                backoff_seconds = min(backoff_seconds * 2, 3600)  # Максимум 1 година
                continue
                
            # Чекаємо 24 години перед наступним скануванням (для демо - можна зменшити)
            await asyncio.sleep(86400)

    async def close(self):
        self.is_running = False
        await self.crawler.close()
        await self.evaluator.close()
