"""
Connector Factory — PREDATOR Analytics
Автоматична генерація коду конекторів за допомогою AI (Gemini / LiteLLM).
"""
import logging
from typing import Dict, Any, Optional

import litellm

logger = logging.getLogger(__name__)

class ConnectorFactory:
    """Використовує AI для генерації Python Harvester-ів з OpenAPI/JSON схем."""

    def __init__(self, model: str = "gemini/gemini-1.5-flash"):
        self.model = model
        self.output_dir = "/Users/Shared/Predator_60/services/ingestion-worker/app/harvesters/auto_generated/"

    async def generate_connector(self, source_metadata: Dict[str, Any]) -> Optional[str]:
        """
        Генерує код конектора (Harvester).
        Повертає шлях до згенерованого файлу, або None у разі помилки.
        """
        logger.info(f"Generating connector for {source_metadata.get('name')}")
        
        prompt = f"""
        Ти архітектор даних PREDATOR Analytics. Твоє завдання - написати Python код для Harvester, 
        який витягуватиме дані з наступного API:
        
        Source Name: {source_metadata.get('name')}
        URL: {source_metadata.get('url')}
        Type: {source_metadata.get('source_type')}
        
        Вимоги:
        1. Використовуй httpx.AsyncClient.
        2. Додай логування.
        3. Створи клас `AutoGeneratedHarvester_{source_metadata.get('name', 'Unknown').replace('-', '_')}`.
        4. Метод `harvest()` має повертати асинхронний генератор даних (yield items).
        5. Не пиши нічого крім Python коду. Без Markdown форматування (```python).
        """
        
        try:
            # Використовуємо LiteLLM для генерації коду
            response = await litellm.acompletion(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1
            )
            
            code = response.choices[0].message.content.strip()
            
            # Видаляємо маркдаун якщо LLM все ж додала його
            if code.startswith("```python"):
                code = code[9:]
            if code.endswith("```"):
                code = code[:-3]
                
            safe_name = source_metadata.get('name', 'unknown').replace("-", "_").lower()
            file_path = f"{self.output_dir}{safe_name}_harvester.py"
            
            # Записуємо згенерований код у файл
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
                
            logger.info(f"Connector successfully generated: {file_path}")
            return file_path
            
        except Exception as e:
            logger.error(f"Failed to generate connector for {source_metadata.get('name')}: {e}")
            return None

    async def generate_normalizer(self, source_metadata: Dict[str, Any]) -> Optional[str]:
        """Генерує клас Normalizer для перетворення сирих даних у сутності."""
        logger.info(f"Generating normalizer for {source_metadata.get('name')}")
        
        prompt = f"""
        Ти архітектор даних PREDATOR Analytics. Твоє завдання - написати Python клас Normalizer 
        для даних з наступного джерела:
        
        Source Name: {source_metadata.get('name')}
        URL: {source_metadata.get('url')}
        
        Вимоги:
        1. Створи клас `AutoGeneratedNormalizer_{source_metadata.get('name', 'Unknown').replace('-', '_')}`.
        2. Додай метод `normalize(raw_data: dict) -> list`, який повертає масив нормалізованих сутностей.
        3. Не пиши нічого крім Python коду.
        """
        try:
            response = await litellm.acompletion(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1
            )
            code = response.choices[0].message.content.strip()
            if code.startswith("```python"): code = code[9:]
            if code.endswith("```"): code = code[:-3]
                
            safe_name = source_metadata.get('name', 'unknown').replace("-", "_").lower()
            file_path = f"/Users/Shared/Predator_60/services/ingestion-worker/app/normalizers/auto_generated/{safe_name}_normalizer.py"
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
            logger.info(f"Normalizer successfully generated: {file_path}")
            return file_path
        except Exception as e:
            logger.error(f"Failed to generate normalizer for {source_metadata.get('name')}: {e}")
            return None

    async def generate_pipeline(self, source_metadata: Dict[str, Any]) -> Optional[str]:
        """Генерує клас Pipeline для оркестрації викачування і нормалізації."""
        logger.info(f"Generating pipeline for {source_metadata.get('name')}")
        
        prompt = f"""
        Ти архітектор даних PREDATOR Analytics. Твоє завдання - написати Python клас Pipeline 
        для оркестрації ETL з наступного джерела:
        
        Source Name: {source_metadata.get('name')}
        
        Вимоги:
        1. Створи клас `AutoGeneratedPipeline_{source_metadata.get('name', 'Unknown').replace('-', '_')}`.
        2. Додай метод `run()`, який з'єднуватиме Harvester та Normalizer.
        3. Не пиши нічого крім Python коду.
        """
        try:
            response = await litellm.acompletion(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1
            )
            code = response.choices[0].message.content.strip()
            if code.startswith("```python"): code = code[9:]
            if code.endswith("```"): code = code[:-3]
                
            safe_name = source_metadata.get('name', 'unknown').replace("-", "_").lower()
            file_path = f"/Users/Shared/Predator_60/services/ingestion-worker/app/pipelines/auto_generated/{safe_name}_pipeline.py"
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
            logger.info(f"Pipeline successfully generated: {file_path}")
            return file_path
        except Exception as e:
            logger.error(f"Failed to generate pipeline for {source_metadata.get('name')}: {e}")
            return None
