"""
Connector Factory — PREDATOR Analytics
Автоматична генерація коду конекторів за допомогою AI (Gemini / LiteLLM).
"""
import logging
import os
from typing import Dict, Any, Optional
from pathlib import Path

import litellm

logger = logging.getLogger(__name__)

class ConnectorFactory:
    """Використовує AI для генерації Python Harvester-ів з OpenAPI/JSON схем."""

    def __init__(self, model: str = None):
        # Allow override from env var, default to gemini-1.5-flash but formatted correctly for litellm
        self.model = model or os.getenv("LITELLM_MODEL", "gemini/gemini-1.5-flash")
        
        # Визначаємо кореневу директорію проєкту автоматично
        self.project_root = Path(__file__).resolve().parent.parent.parent.parent.parent
        self.ingestion_worker_dir = self.project_root / "services" / "ingestion-worker" / "app"
        
        self.harvester_dir = self.ingestion_worker_dir / "harvesters" / "autogen"
        self.normalizer_dir = self.ingestion_worker_dir / "normalizers" / "autogen"
        self.pipeline_dir = self.ingestion_worker_dir / "pipelines" / "autogen"
        
        # Створюємо директорії, якщо їх немає
        os.makedirs(self.harvester_dir, exist_ok=True)
        os.makedirs(self.normalizer_dir, exist_ok=True)
        os.makedirs(self.pipeline_dir, exist_ok=True)

    def _clean_code(self, code: str) -> str:
        """Видаляє markdown артефакти з відповіді LLM."""
        code = code.strip()
        if code.startswith("```python"):
            code = code[9:]
        elif code.startswith("```"):
            code = code[3:]
        if code.endswith("```"):
            code = code[:-3]
        return code.strip()

    async def generate_connector(self, source_metadata: Dict[str, Any]) -> Optional[str]:
        """Генерує код конектора (Harvester)."""
        logger.info(f"Generating connector for {source_metadata.get('name')}")
        
        prompt = f"""Ти - PREDATOR AI Factory. Згенеруй Python-код для Harvester (збір даних з API).
Джерело: {source_metadata.get('name')}
Базовий URL: {source_metadata.get('url')}
Метадані: {source_metadata}

Вимоги:
1. Створи клас `AutoGeneratedHarvester_{source_metadata.get('id', 'Unknown').replace('-', '_').lower()}`.
2. Не використовуй успадкування, це має бути самостійний клас.
3. Має бути метод `async def harvest(self)`, який робить HTTP запити (через httpx) та повертає дані через yield (асинхронний генератор).
4. Код має бути синтаксично правильним Python, готовим до виконання. Не пиши пояснень, тільки код.
"""
        
        try:
            response = await litellm.acompletion(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1
            )
            
            code = self._clean_code(response.choices[0].message.content)
            safe_name = source_metadata.get('id', 'unknown').replace("-", "_").lower()
            file_path = self.harvester_dir / f"{safe_name}_harvester.py"
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
                
            logger.info(f"Connector successfully generated: {file_path}")
            return str(file_path)
            
        except Exception as e:
            logger.error(f"Failed to generate connector for {source_metadata.get('name')}: {e}")
            return None

    async def generate_normalizer(self, source_metadata: Dict[str, Any]) -> Optional[str]:
        """Генерує клас Normalizer для перетворення сирих даних у сутності."""
        logger.info(f"Generating normalizer for {source_metadata.get('name')}")
        
        prompt = f"""
        Ти архітектор даних PREDATOR Analytics. Твоє завдання - написати Python клас Normalizer 
        для даних з наступного джерела:
        
        Source Name: {source_metadata.get('name')}
        
        Вимоги:
        1. Створи клас `AutoGeneratedNormalizer_{source_metadata.get('name', 'Unknown').replace('-', '_').replace(' ', '')}`.
        2. Додай метод `def normalize(self, raw_data: dict) -> list`, який повертає масив нормалізованих сутностей.
        3. Не пиши нічого крім Python коду.
        """
        try:
            response = await litellm.acompletion(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1
            )
            code = self._clean_code(response.choices[0].message.content)
            safe_name = source_metadata.get('id', 'unknown').replace("-", "_").lower()
            file_path = self.normalizer_dir / f"{safe_name}_normalizer.py"
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
                
            logger.info(f"Normalizer successfully generated: {file_path}")
            return str(file_path)
        except Exception as e:
            logger.error(f"Failed to generate normalizer for {source_metadata.get('name')}: {e}")
            return None

    async def generate_pipeline(self, source_metadata: Dict[str, Any]) -> Optional[str]:
        """Генерує клас Pipeline для оркестрації викачування і нормалізації."""
        logger.info(f"Generating pipeline for {source_metadata.get('name')}")
        
        prompt = f"""
        Ти архітектор даних PREDATOR Analytics. Твоє завдання - написати Python клас Pipeline 
        для оркестрації ETL з наступного джерела:
        
        Source Name: {source_metadata.get('name')}
        
        Вимоги:
        1. Створи клас `AutoGeneratedPipeline_{source_metadata.get('name', 'Unknown').replace('-', '_').replace(' ', '')}`.
        2. Додай метод `async def run(self)`, який з'єднуватиме Harvester та Normalizer.
        3. Не пиши нічого крім Python коду.
        """
        try:
            response = await litellm.acompletion(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1
            )
            code = self._clean_code(response.choices[0].message.content)
            safe_name = source_metadata.get('id', 'unknown').replace("-", "_").lower()
            file_path = self.pipeline_dir / f"{safe_name}_pipeline.py"
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
                
            logger.info(f"Pipeline successfully generated: {file_path}")
            return str(file_path)
        except Exception as e:
            logger.error(f"Failed to generate pipeline for {source_metadata.get('name')}: {e}")
            return None
