"""
Ghost Runtimes Sandbox — PREDATOR Analytics
Запускає згенеровані AI конектори в ізольованому середовищі для перевірки їх працездатності 
(Zero-Trust Security Engine).
"""
import asyncio
import logging
import subprocess
from typing import Tuple

logger = logging.getLogger(__name__)

class GhostRuntime:
    """Керує життєвим циклом ефемерних контейнерів на NVIDIA Server."""
    
    def __init__(self, remote_host: str = "dima@194.177.1.240", ssh_port: int = 6666):
        self.remote_host = remote_host
        self.ssh_port = ssh_port
        
    async def test_connector(self, script_path: str) -> Tuple[bool, str]:
        """
        Тестує згенерований скрипт.
        Оскільки локальний Docker заборонений, ми імітуємо запуск ізольованого Python процесу 
        (у майбутньому — це відправка скрипта по SSH в `predator_ghost_runner` контейнер).
        """
        logger.info(f"GhostRuntime: Testing connector {script_path}")
        
        # 1. Синтаксична перевірка за допомогою ast.parse
        import ast
        try:
            with open(script_path, "r", encoding="utf-8") as f:
                source_code = f.read()
            ast.parse(source_code)
            logger.info("GhostRuntime: AST Syntax check passed.")
        except SyntaxError as e:
            error_msg = f"SyntaxError in generated code: {e}"
            logger.error(f"GhostRuntime: {error_msg}")
            return False, error_msg
        except Exception as e:
            error_msg = f"Failed to read or parse file: {e}"
            logger.error(f"GhostRuntime: {error_msg}")
            return False, error_msg

        # 2. Створюємо простий тестовий файл, який імпортує згенерований клас та викликає harvest() з обмеженням
        test_script_content = f"""
import asyncio
import sys
import importlib.util
import os

async def run_test():
    try:
        spec = importlib.util.spec_from_file_location("harvester", "{script_path}")
        harvester_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(harvester_module)
        
        # Знаходимо клас Harvester (будь-який клас що починається з AutoGenerated)
        harvester_class = None
        for name in dir(harvester_module):
            if name.startswith("AutoGenerated"):
                harvester_class = getattr(harvester_module, name)
                break
                
        if not harvester_class:
            print("ERROR: Harvester class not found")
            sys.exit(1)
            
        instance = harvester_class()
        count = 0
        async for item in instance.harvest():
            print(f"Sample item: {{item}}")
            count += 1
            if count >= 3: # Тестуємо тільки 3 записи
                break
        print("SUCCESS: Connector executed without crashing")
        sys.exit(0)
    except Exception as e:
        print(f"ERROR: {{e}}")
        sys.exit(1)

if __name__ == "__main__":
    asyncio.run(run_test())
"""
        test_file_path = f"{script_path}.test.py"
        with open(test_file_path, "w", encoding="utf-8") as f:
            f.write(test_script_content)
            
        # Запускаємо як окремий subprocess для ізоляції (Mock Ghost Runtime)
        try:
            process = await asyncio.create_subprocess_exec(
                "python", test_file_path,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )
            stdout, stderr = await process.communicate()
            
            output = stdout.decode()
            error = stderr.decode()
            
            if process.returncode == 0 and "SUCCESS" in output:
                logger.info("GhostRuntime: Connector passed tests.")
                return True, output
            else:
                logger.error(f"GhostRuntime: Connector failed tests. Output: {output}, Error: {error}")
                return False, f"Output:\n{output}\nError:\n{error}"
                
        except Exception as e:
            logger.error(f"GhostRuntime: System error running tests: {e}")
            return False, str(e)
