apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predator-kaggle
  namespace: argocd
spec:
  project: predator-project
  source:
    repoURL: https://github.com/dima1203oleg/predator-analytics.git
    targetRevision: HEAD
    path: deploy/helm/predator
    helm:
      valueFiles:
        - values.yaml
        - values-kaggle.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: predator-elite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
