---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  root-password: {{ .Values.minio.auth.rootPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.auth.password | quote }}

{{- if .Values.monitoring.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  admin-password: {{ .Values.monitoring.grafana.adminPassword | quote }}
{{- end }}
