apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predator-nvidia
  namespace: argocd
  labels:
    env: lab-gpu
    app: predator
spec:
  project: default
  source:
    repoURL: https://github.com/dima1203oleg/predator-analytics
    targetRevision: main
    path: environments/nvidia
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: predator-nvidia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m