apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predator-nvidia  # Назва Application для ArgoCD на NVIDIA
  namespace: argocd  # ArgoCD працює в цьому namespace
spec:
  project: default  # Проект ArgoCD (default для простоти)
  source:
    repoURL: https://github.com/dima1203oleg/predator-analytics  # URL GitHub-репозиторію
    targetRevision: main  # Гілка для відстеження
    path: environments/nvidia  # Шлях до Helm-чарту для NVIDIA
    helm:  # Якщо це Helm-чарт
      valueFiles:
        - values.yaml  # Файл значень для NVIDIA
  destination:
    server: https://kubernetes.default.svc  # Кластер NVIDIA (замінити на реальний)
    namespace: predator-nvidia  # Namespace для деплою на NVIDIA
  syncPolicy:
    automated:  # Автоматична синхронізація
      prune: true  # Видаляти ресурси, яких немає в Git
      selfHeal: true  # Автоматично виправляти відхилення