apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predator-oracle  # Назва Application для ArgoCD на Oracle
  namespace: argocd  # ArgoCD працює в цьому namespace
spec:
  project: default  # Проект ArgoCD (default для простоти)
  source:
    repoURL: https://github.com/dima1203oleg/predator-analytics  # URL GitHub-репозиторію
    targetRevision: main  # Гілка для відстеження
    path: environments/oracle  # Шлях до Helm-чарту для Oracle
    helm:  # Якщо це Helm-чарт
      valueFiles:
        - values.yaml  # Файл значень для Oracle
  destination:
    server: https://kubernetes.default.svc  # Кластер Oracle (замінити на реальний)
    namespace: predator-oracle  # Namespace для деплою на Oracle
  syncPolicy:
    automated:  # Автоматична синхронізація
      prune: true  # Видаляти ресурси, яких немає в Git
      selfHeal: true  # Автоматично виправляти відхилення