import React, { useState, useEffect } from 'react';
import { 
  Bot, Globe, Database, FileCode2, Play, Square, 
  Activity, CheckCircle2, AlertTriangle, ChevronRight,
  ShieldCheck, Cpu, Terminal, Zap
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface DiscoveredSource {
  id: string;
  name: string;
  url: string;
  type: string;
  priority: number;
  status: 'DISCOVERED' | 'GENERATING' | 'TESTING' | 'DEPLOYED' | 'FAILED';
  format: string;
}

const MOCK_SOURCES: DiscoveredSource[] = [
  { id: '1', name: 'OpenSanctions API', url: 'https://api.opensanctions.org', type: 'openapi', priority: 95, status: 'DEPLOYED', format: 'JSON' },
  { id: '2', name: 'Data.gov.ua (Prozorro)', url: 'https://data.gov.ua/api/3/action', type: 'ckan', priority: 85, status: 'DEPLOYED', format: 'JSON' },
  { id: '3', name: 'CourtListener REST', url: 'https://www.courtlistener.com/api/rest/v3/', type: 'rest', priority: 70, status: 'DISCOVERED', format: 'JSON' },
  { id: '4', name: 'NBU Open Data', url: 'https://bank.gov.ua/NBU_Exchange/exchange', type: 'xml_feed', priority: 65, status: 'DISCOVERED', format: 'XML' },
  { id: '5', name: 'EDR Registry Dump', url: 'ftp://data.gov.ua/edr_dump.csv', type: 'bulk_dump', priority: 55, status: 'DISCOVERED', format: 'CSV' },
];

export default function AutonomousFactoryTab() {
  const [isRunning, setIsRunning] = useState(false);
  const [sources, setSources] = useState<DiscoveredSource[]>(MOCK_SOURCES);
  const [selectedSource, setSelectedSource] = useState<DiscoveredSource | null>(null);
  const [logs, setLogs] = useState<string[]>([
    "[SYSTEM] Autonomous Discovery Layer Ready.",
    "[SYSTEM] Awaiting crawler activation..."
  ]);

  const addLog = (msg: string) => {
    setLogs(prev => [...prev.slice(-15), msg]); // Keep last 15 logs
  };

  const startFactoryCycle = (source: DiscoveredSource) => {
    if (source.status === 'DEPLOYED' || source.status === 'GENERATING') return;
    
    setSelectedSource(source);
    
    // Simulate generation process
    const updateStatus = (id: string, newStatus: any) => {
      setSources(prev => prev.map(s => s.id === id ? { ...s, status: newStatus } : s));
    };

    updateStatus(source.id, 'GENERATING');
    addLog(`[FACTORY] Initiating LLM Connector Generation for ${source.name}...`);
    
    setTimeout(() => {
      addLog(`[FACTORY] Analyzing schema from ${source.url}`);
      addLog(`[FACTORY] Generating Python Harvester class...`);
      
      setTimeout(() => {
        updateStatus(source.id, 'TESTING');
        addLog(`[GHOST_RUNTIME] Deploying AutoGeneratedHarvester to Sandbox...`);
        addLog(`[GHOST_RUNTIME] Executing test fetch (limit: 3 records)...`);
        
        setTimeout(() => {
          updateStatus(source.id, 'DEPLOYED');
          addLog(`[GHOST_RUNTIME] SUCCESS: Connector verified. Zero crashes.`);
          addLog(`[SYSTEM] Connector ${source.name} automatically deployed to Ingestion Worker.`);
        }, 2500);
      }, 2500);
    }, 1500);
  };

  const toggleCrawler = () => {
    setIsRunning(!isRunning);
    if (!isRunning) {
      addLog("[CRAWLER] Activated. Scanning internet directories (CKAN, APIs.guru, OData)...");
    } else {
      addLog("[CRAWLER] Halted. Entering sleep mode.");
    }
  };

  return (
    <div className="h-full w-full flex flex-col p-6 space-y-6 text-slate-200">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-black text-white flex items-center gap-3">
            <Cpu className="w-8 h-8 text-blue-500" />
            AUTONOMOUS FACTORY
          </h1>
          <p className="text-slate-400 mt-1">Sovereign Discovery Layer & AI Connector Generator</p>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 bg-slate-900 border border-slate-800 px-4 py-2 rounded-lg">
            <Activity className={`w-5 h-5 ${isRunning ? 'text-green-500 animate-pulse' : 'text-slate-600'}`} />
            <span className="font-mono text-sm uppercase">
              {isRunning ? 'Crawler Active' : 'Crawler Standby'}
            </span>
          </div>
          <button
            onClick={toggleCrawler}
            className={`flex items-center gap-2 px-6 py-2 rounded-lg font-bold transition-all ${
              isRunning 
                ? 'bg-red-500/10 text-red-500 hover:bg-red-500/20 border border-red-500/50' 
                : 'bg-emerald-500/10 text-emerald-500 hover:bg-emerald-500/20 border border-emerald-500/50'
            }`}
          >
            {isRunning ? <Square className="w-4 h-4 fill-current" /> : <Play className="w-4 h-4 fill-current" />}
            {isRunning ? 'STOP CRAWLER' : 'START CRAWLER'}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-12 gap-6 h-[calc(100%-80px)]">
        {/* Left Panel: Discovered Sources */}
        <div className="col-span-7 bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden flex flex-col">
          <div className="p-4 border-b border-slate-800 bg-slate-900/50 flex justify-between items-center">
            <h2 className="font-bold text-white flex items-center gap-2">
              <Globe className="w-5 h-5 text-indigo-400" />
              Meta-Graph Sources
            </h2>
            <span className="text-xs bg-indigo-500/20 text-indigo-300 px-2 py-1 rounded-full border border-indigo-500/30">
              Discovered: {sources.length}
            </span>
          </div>
          
          <div className="flex-1 overflow-y-auto p-4 space-y-3">
            {sources.map(source => (
              <div 
                key={source.id} 
                className={`p-4 rounded-xl border transition-all ${
                  selectedSource?.id === source.id 
                    ? 'bg-blue-900/20 border-blue-500/50' 
                    : 'bg-black/40 border-white/5 hover:border-white/20'
                }`}
              >
                <div className="flex justify-between items-start">
                  <div>
                    <h3 className="font-bold text-lg text-white flex items-center gap-2">
                      {source.name}
                      {source.priority >= 80 && <Zap className="w-4 h-4 text-amber-400 fill-amber-400" />}
                    </h3>
                    <p className="text-xs text-slate-400 font-mono mt-1">{source.url}</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="text-right">
                      <div className="text-xs text-slate-500 uppercase">Priority</div>
                      <div className={`font-mono font-bold text-lg ${
                        source.priority >= 80 ? 'text-amber-400' : 
                        source.priority >= 60 ? 'text-emerald-400' : 'text-blue-400'
                      }`}>
                        {source.priority}
                      </div>
                    </div>
                  </div>
                </div>
                
                <div className="mt-4 flex justify-between items-center">
                  <div className="flex gap-2">
                    <span className="text-[10px] uppercase bg-slate-800 text-slate-300 px-2 py-0.5 rounded-sm">
                      {source.type}
                    </span>
                    <span className="text-[10px] uppercase bg-slate-800 text-slate-300 px-2 py-0.5 rounded-sm">
                      {source.format}
                    </span>
                  </div>
                  
                  <div className="flex items-center gap-3">
                    {source.status === 'DEPLOYED' && (
                      <span className="flex items-center gap-1.5 text-xs text-emerald-400 font-medium">
                        <CheckCircle2 className="w-4 h-4" /> Integrated
                      </span>
                    )}
                    {source.status === 'GENERATING' && (
                      <span className="flex items-center gap-1.5 text-xs text-blue-400 font-medium animate-pulse">
                        <Terminal className="w-4 h-4" /> Generating Code...
                      </span>
                    )}
                    {source.status === 'TESTING' && (
                      <span className="flex items-center gap-1.5 text-xs text-amber-400 font-medium animate-pulse">
                        <ShieldCheck className="w-4 h-4" /> Sandboxing...
                      </span>
                    )}
                    {source.status === 'DISCOVERED' && (
                      <button 
                        onClick={() => startFactoryCycle(source)}
                        className="flex items-center gap-1.5 text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-3 py-1.5 rounded-md transition-colors"
                      >
                        <Bot className="w-3.5 h-3.5" /> Auto-Integrate
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Right Panel: Factory Terminal & Active Connectors */}
        <div className="col-span-5 flex flex-col gap-6">
          
          {/* Terminal */}
          <div className="bg-black border border-slate-800 rounded-2xl overflow-hidden flex flex-col flex-1">
            <div className="p-3 border-b border-slate-800 bg-slate-900/80 flex items-center gap-2">
              <Terminal className="w-4 h-4 text-slate-400" />
              <span className="text-xs font-mono text-slate-400">factory_daemon.log</span>
            </div>
            <div className="p-4 flex-1 overflow-y-auto font-mono text-[11px] text-emerald-500/80 space-y-2">
              <AnimatePresence>
                {logs.map((log, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="flex items-start gap-2"
                  >
                    <span className="text-slate-600 select-none">{`>`}</span>
                    <span className={
                      log.includes('SUCCESS') ? 'text-emerald-400 font-bold' :
                      log.includes('ERROR') ? 'text-red-400 font-bold' :
                      log.includes('FACTORY') ? 'text-blue-400' :
                      log.includes('GHOST_RUNTIME') ? 'text-amber-400' : ''
                    }>{log}</span>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </div>

          {/* Connectors Overview */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5">
             <h3 className="font-bold text-white mb-4 flex items-center gap-2">
                <FileCode2 className="w-5 h-5 text-emerald-400" />
                Active Auto-Connectors
             </h3>
             <div className="space-y-3">
                {sources.filter(s => s.status === 'DEPLOYED').map(source => (
                  <div key={source.id} className="flex justify-between items-center p-3 bg-black/40 rounded-lg border border-white/5">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-emerald-500/10 flex items-center justify-center border border-emerald-500/20">
                        <Bot className="w-4 h-4 text-emerald-500" />
                      </div>
                      <div>
                        <div className="text-sm font-bold text-slate-200">{source.name.replace(/\s+/g, '')}Harvester</div>
                        <div className="text-[10px] text-slate-500">v1.0 • Autonomous</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-1 text-[10px] text-emerald-400">
                      <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                      ONLINE
                    </div>
                  </div>
                ))}
             </div>
          </div>

        </div>
      </div>
    </div>
  );
}
