"""v55 influence scores

Revision ID: 20260304_0024_v55_influence
Revises: 20260304_0023_v55_behav_aggregate
Create Date: 2026-03-04 09:15:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '20260304_0024_v55_influence'
down_revision = '20260304_0023_v55_behav_aggregate'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influence_scores',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('ueid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('im', sa.Float(), nullable=False, comment='Influence Multiplier'),
        sa.Column('hci', sa.Float(), nullable=False, comment='Hidden Control Index'),
        sa.Column('shadow_cluster_score', sa.Float(), nullable=False, comment='Shadow Cluster Score'),
        sa.Column('aggregate', sa.Float(), server_default='0', nullable=False, comment='Weighted aggregate 0-100'),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['ueid'], ['v55.entities.ueid'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='v55'
    )
    op.create_index('idx_influence_ueid', 'influence_scores', ['ueid', 'calculated_at'], unique=False, schema='v55')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_influence_ueid', table_name='influence_scores', schema='v55')
    op.drop_table('influence_scores', schema='v55')
    # ### end Alembic commands ###
