"""v55_fused_records

Revision ID: 2d500e307145
Revises: 0001_v55_baseline
Create Date: 2026-03-03 04:12:41.626437+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d500e307145'
down_revision: str | None = '0001_v55_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fused_records',
    sa.Column('record_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ueid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ueid'], ['v55.entities.ueid'], ),
    sa.PrimaryKeyConstraint('record_id'),
    schema='v55'
    )
    op.create_index('idx_fused_fingerprint', 'fused_records', ['fingerprint'], unique=False, schema='v55')
    op.create_index('idx_fused_source', 'fused_records', ['source'], unique=False, schema='v55')
    op.create_index('idx_fused_ueid', 'fused_records', ['ueid'], unique=False, schema='v55')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fused_ueid', table_name='fused_records', schema='v55')
    op.drop_index('idx_fused_source', table_name='fused_records', schema='v55')
    op.drop_index('idx_fused_fingerprint', table_name='fused_records', schema='v55')
    op.drop_table('fused_records', schema='v55')
    # ### end Alembic commands ###
