"""v55 remaining engines

Revision ID: 20260304_0025_v55_engines_final
Revises: 20260304_0024_v55_influence_scores
Create Date: 2026-03-04 09:20:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260304_0025_v55_engines_final'
down_revision = '20260304_0024_v55_influence'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_scores',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('ueid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('aai', sa.Float(), nullable=False, comment='Average Approval Index'),
        sa.Column('pls', sa.Float(), nullable=False, comment='Post Loyalty Score'),
        sa.Column('rdi', sa.Float(), nullable=False, comment='Regional Divergence Index'),
        sa.Column('rsi', sa.Float(), nullable=False, comment='Regulatory Shift Index'),
        sa.Column('aggregate', sa.Float(), server_default='0', nullable=False, comment='Weighted aggregate 0-100'),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['ueid'], ['v55.entities.ueid'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='v55'
    )
    op.create_index('idx_institutional_ueid', 'institutional_scores', ['ueid', 'calculated_at'], unique=False, schema='v55')

    op.create_table('structural_scores',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('ueid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('mci', sa.Float(), nullable=False, comment='Market Consistency Index'),
        sa.Column('pfi', sa.Float(), nullable=False, comment='Production Flow Index'),
        sa.Column('tdi', sa.Float(), nullable=False, comment='Trade Discrepancy Index'),
        sa.Column('lgs', sa.Float(), nullable=False, comment='Logistics Gap Score'),
        sa.Column('aggregate', sa.Float(), server_default='0', nullable=False, comment='Weighted aggregate 0-100'),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['ueid'], ['v55.entities.ueid'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='v55'
    )
    op.create_index('idx_structural_ueid', 'structural_scores', ['ueid', 'calculated_at'], unique=False, schema='v55')

    op.create_table('predictive_scores',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('ueid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('disappearance_risk', sa.Float(), nullable=False, comment='Disappearance Risk'),
        sa.Column('regulatory_intervention_risk', sa.Float(), nullable=False, comment='Regulatory Intervention Risk'),
        sa.Column('concentration_risk', sa.Float(), nullable=False, comment='Concentration Risk'),
        sa.Column('scheme_emergence_risk', sa.Float(), nullable=False, comment='Scheme Emergence Risk'),
        sa.Column('aggregate', sa.Float(), server_default='0', nullable=False, comment='Weighted aggregate 0-100'),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['ueid'], ['v55.entities.ueid'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='v55'
    )
    op.create_index('idx_predictive_ueid', 'predictive_scores', ['ueid', 'calculated_at'], unique=False, schema='v55')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_predictive_ueid', table_name='predictive_scores', schema='v55')
    op.drop_table('predictive_scores', schema='v55')

    op.drop_index('idx_structural_ueid', table_name='structural_scores', schema='v55')
    op.drop_table('structural_scores', schema='v55')

    op.drop_index('idx_institutional_ueid', table_name='institutional_scores', schema='v55')
    op.drop_table('institutional_scores', schema='v55')
    # ### end Alembic commands ###
