enabled: true
replicaCount: 1
image:
  repository: "europe-west3-docker.pkg.dev/project-b63e383c-4a98-418d-837/predator-repo/graph-service"
  tag: "latest"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8002
resources:
  requests:
    cpu: 5m
    memory: 32Mi
  limits:
    cpu: 5m
    memory: 32Mi
