class AutoGeneratedNormalizer_Судитазаконодавство:
    def normalize(self, raw_data: dict) -> list:
        normalized_entities = []
        if isinstance(raw_data, dict):
            for key, value in raw_data.items():
                if isinstance(value, dict):
                    normalized_entities.append(value)
                elif isinstance(value, list):
                    for item in value:
                        if isinstance(item, dict):
                            normalized_entities.append(item)
        return normalized_entities