class AutoGeneratedNormalizer_ПЕПтасанкції:
    def normalize(self, raw_data: dict) -> list:
        normalized_entities = []
        if not raw_data:
            return normalized_entities

        for entity in raw_data.get('entities', []):
            normalized_entity = {
                'id': entity.get('id'),
                'full_name': entity.get('full_name'),
                'sanction_type': entity.get('sanction_type'),
                'country': entity.get('country'),
                'date_of_birth': entity.get('date_of_birth'),
                'position': entity.get('position'),
                'source': 'ПЕП та санкції'
            }
            normalized_entities.append(normalized_entity)

        return normalized_entities