class AutoGeneratedNormalizer_Державніреєстри:
    def normalize(self, raw_data: dict) -> list:
        normalized_entities = []
        if raw_data:
            for key, value in raw_data.items():
                normalized_entity = {
                    "source": "Державні реєстри",
                    "entity_type": key,
                    "data": value
                }
                normalized_entities.append(normalized_entity)
        return normalized_entities