class AutoGeneratedNormalizer_Державніреєстри:
    def normalize(self, raw_data: dict) -> list:
        normalized_entities = []
        if raw_data:
            normalized_entity = {
                "source_name": "Державні реєстри",
                "data": raw_data
            }
            normalized_entities.append(normalized_entity)
        return normalized_entities