class AutoGeneratedNormalizer_Тендеритафінанси:
    def normalize(self, raw_data: dict) -> list:
        normalized_entities = []
        if not raw_data:
            return normalized_entities

        # Припускаємо, що дані мають структуру з полями 'tenders' і 'finances'
        tenders = raw_data.get('tenders', [])
        finances = raw_data.get('finances', [])

        # Нормалізація тендерів
        for tender in tenders:
            normalized_entity = {
                'entity_type': 'tender',
                'id': tender.get('id'),
                'title': tender.get('title'),
                'amount': tender.get('amount'),
                'status': tender.get('status'),
                'date': tender.get('date')
            }
            normalized_entities.append(normalized_entity)

        # Нормалізація фінансових даних
        for finance in finances:
            normalized_entity = {
                'entity_type': 'finance',
                'id': finance.get('id'),
                'description': finance.get('description'),
                'amount': finance.get('amount'),
                'currency': finance.get('currency'),
                'date': finance.get('date')
            }
            normalized_entities.append(normalized_entity)

        return normalized_entities