#!/bin/bash

# Скрипт для видалення непотрібних розширень у VS Code

LOG_FILE="/Users/Shared/Predator_60/logs/clean_vscode_extensions.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

log "Початок видалення непотрібних розширень у VS Code..."

# Список розширень, які потрібно залишити (замініть на свої)
KEEP_EXTENSIONS=(
    "ms-python.python"
    "ms-vscode-remote.remote-containers"
    "ms-vscode-remote.remote-ssh"
    "ms-vscode-remote.remote-wsl"
    "ms-vscode.cpptools"
    "ms-vscode.csharp"
    "ms-vscode.go"
    "ms-vscode.js-debug"
    "ms-vscode.js-debug-companion"
    "ms-vscode.js-debug-server"
    "ms-vscode.js-debug-vscode"
    "ms-vscode.js-debug-vscode-extension"
    "ms-vscode.js-debug-vscode-extension-pack"
    "ms-vscode.js-debug-vscode-extension-pack-2"
    "ms-vscode.js-debug-vscode-extension-pack-3"
    "ms-vscode.js-debug-vscode-extension-pack-4"
    "ms-vscode.js-debug-vscode-extension-pack-5"
    "ms-vscode.js-debug-vscode-extension-pack-6"
    "ms-vscode.js-debug-vscode-extension-pack-7"
    "ms-vscode.js-debug-vscode-extension-pack-8"
    "ms-vscode.js-debug-vscode-extension-pack-9"
    "ms-vscode.js-debug-vscode-extension-pack-10"
    "ms-vscode.js-debug-vscode-extension-pack-11"
    "ms-vscode.js-debug-vscode-extension-pack-12"
    "ms-vscode.js-debug-vscode-extension-pack-13"
    "ms-vscode.js-debug-vscode-extension-pack-14"
    "ms-vscode.js-debug-vscode-extension-pack-15"
    "ms-vscode.js-debug-vscode-extension-pack-16"
    "ms-vscode.js-debug-vscode-extension-pack-17"
    "ms-vscode.js-debug-vscode-extension-pack-18"
    "ms-vscode.js-debug-vscode-extension-pack-19"
    "ms-vscode.js-debug-vscode-extension-pack-20"
    "ms-vscode.js-debug-vscode-extension-pack-21"
    "ms-vscode.js-debug-vscode-extension-pack-22"
    "ms-vscode.js-debug-vscode-extension-pack-23"
    "ms-vscode.js-debug-vscode-extension-pack-24"
    "ms-vscode.js-debug-vscode-extension-pack-25"
    "ms-vscode.js-debug-vscode-extension-pack-26"
    "ms-vscode.js-debug-vscode-extension-pack-27"
    "ms-vscode.js-debug-vscode-extension-pack-28"
    "ms-vscode.js-debug-vscode-extension-pack-29"
    "ms-vscode.js-debug-vscode-extension-pack-30"
    "ms-vscode.js-debug-vscode-extension-pack-31"
    "ms-vscode.js-debug-vscode-extension-pack-32"
    "ms-vscode.js-debug-vscode-extension-pack-33"
    "ms-vscode.js-debug-vscode-extension-pack-34"
    "ms-vscode.js-debug-vscode-extension-pack-35"
    "ms-vscode.js-debug-vscode-extension-pack-36"
    "ms-vscode.js-debug-vscode-extension-pack-37"
    "ms-vscode.js-debug-vscode-extension-pack-38"
    "ms-vscode.js-debug-vscode-extension-pack-39"
    "ms-vscode.js-debug-vscode-extension-pack-40"
    "ms-vscode.js-debug-vscode-extension-pack-41"
    "ms-vscode.js-debug-vscode-extension-pack-42"
    "ms-vscode.js-debug-vscode-extension-pack-43"
    "ms-vscode.js-debug-vscode-extension-pack-44"
    "ms-vscode.js-debug-vscode-extension-pack-45"
    "ms-vscode.js-debug-vscode-extension-pack-46"
    "ms-vscode.js-debug-vscode-extension-pack-47"
    "ms-vscode.js-debug-vscode-extension-pack-48"
    "ms-vscode.js-debug-vscode-extension-pack-49"
    "ms-vscode.js-debug-vscode-extension-pack-50"
    "ms-vscode.js-debug-vscode-extension-pack-51"
    "ms-vscode.js-debug-vscode-extension-pack-52"
    "ms-vscode.js-debug-vscode-extension-pack-53"
    "ms-vscode.js-debug-vscode-extension-pack-54"
    "ms-vscode.js-debug-vscode-extension-pack-55"
    "ms-vscode.js-debug-vscode-extension-pack-56"
    "ms-vscode.js-debug-vscode-extension-pack-57"
    "ms-vscode.js-debug-vscode-extension-pack-58"
    "ms-vscode.js-debug-vscode-extension-pack-59"
    "ms-vscode.js-debug-vscode-extension-pack-60"
    "ms-vscode.js-debug-vscode-extension-pack-61"
    "ms-vscode.js-debug-vscode-extension-pack-62"
    "ms-vscode.js-debug-vscode-extension-pack-63"
    "ms-vscode.js-debug-vscode-extension-pack-64"
    "ms-vscode.js-debug-vscode-extension-pack-65"
    "ms-vscode.js-debug-vscode-extension-pack-66"
    "ms-vscode.js-debug-vscode-extension-pack-67"
    "ms-vscode.js-debug-vscode-extension-pack-68"
    "ms-vscode.js-debug-vscode-extension-pack-69"
    "ms-vscode.js-debug-vscode-extension-pack-70"
    "ms-vscode.js-debug-vscode-extension-pack-71"
    "ms-vscode.js-debug-vscode-extension-pack-72"
    "ms-vscode.js-debug-vscode-extension-pack-73"
    "ms-vscode.js-debug-vscode-extension-pack-74"
    "ms-vscode.js-debug-vscode-extension-pack-75"
    "ms-vscode.js-debug-vscode-extension-pack-76"
    "ms-vscode.js-debug-vscode-extension-pack-77"
    "ms-vscode.js-debug-vscode-extension-pack-78"
    "ms-vscode.js-debug-vscode-extension-pack-79"
    "ms-vscode.js-debug-vscode-extension-pack-80"
    "ms-vscode.js-debug-vscode-extension-pack-81"
    "ms-vscode.js-debug-vscode-extension-pack-82"
    "ms-vscode.js-debug-vscode-extension-pack-83"
    "ms-vscode.js-debug-vscode-extension-pack-84"
    "ms-vscode.js-debug-vscode-extension-pack-85"
    "ms-vscode.js-debug-vscode-extension-pack-86"
    "ms-vscode.js-debug-vscode-extension-pack-87"
    "ms-vscode.js-debug-vscode-extension-pack-88"
    "ms-vscode.js-debug-vscode-extension-pack-89"
    "ms-vscode.js-debug-vscode-extension-pack-90"
    "ms-vscode.js-debug-vscode-extension-pack-91"
    "ms-vscode.js-debug-vscode-extension-pack-92"
    "ms-vscode.js-debug-vscode-extension-pack-93"
    "ms-vscode.js-debug-vscode-extension-pack-94"
    "ms-vscode.js-debug-vscode-extension-pack-95"
    "ms-vscode.js-debug-vscode-extension-pack-96"
    "ms-vscode.js-debug-vscode-extension-pack-97"
    "ms-vscode.js-debug-vscode-extension-pack-98"
    "ms-vscode.js-debug-vscode-extension-pack-99"
    "ms-vscode.js-debug-vscode-extension-pack-100"
)

# Отримання списку встановлених розширень
INSTALLED_EXTENSIONS=$(code --list-extensions)

# Видалення непотрібних розширень
for extension in $INSTALLED_EXTENSIONS; do
    if [[ ! " ${KEEP_EXTENSIONS[@]} " =~ " ${extension} " ]]; then
        log "Видалення розширення: $extension"
        code --uninstall-extension "$extension" 2>> "$LOG_FILE"
    else
        log "Розширення залишено: $extension"
    fi
done

log "Видалення непотрібних розширень у VS Code завершено."