from datetime import datetime
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field

# ═══════════════════════════════════════════════════════════════════════════
# RAW DATA INGESTION EVENT (Topic: raw-data)
# ═══════════════════════════════════════════════════════════════════════════
class RawIngestionEvent(BaseModel):
    """
    Emitted by ingestion-api after accepting an upload.
    Consumed by workers (worker-excel, worker-pdf, etc.) and normalization-service.
    """
    job_id: str = Field(..., description="Unique ID for the ingestion job")
    tenant_id: str = Field(..., description="ID of the tenant uploading data")
    source_type: str = Field(..., description="Type of data: excel, pdf, telegram_message, etc.")
    source_uri: str = Field(..., description="S3/MinIO path or URI to the raw file/content")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context like original filename")
    timestamp: datetime = Field(default_factory=datetime.utcnow)

# ═══════════════════════════════════════════════════════════════════════════
# NORMALIZED ENTITY EVENT (Topic: normalized-data)
# ═══════════════════════════════════════════════════════════════════════════
class NormalizedEntity(BaseModel):
    """
    Emitted by workers after parsing and normalization-service after entity resolution.
    Consumed by graph-engine, behavioral-engine, institutional-engine.
    """
    ueid: str = Field(..., description="Unique Universal Entity ID generated by normalization-service")
    tenant_id: str = Field(..., description="Tenant ID this data belongs to")
    entity_type: str = Field(..., description="Company, Person, Product, Declaration, etc.")
    attributes: Dict[str, Any] = Field(..., description="Cleaned, typed attributes for the entity")
    source_job_id: str = Field(..., description="Job ID that produced this entity")
    confidence_score: float = Field(default=1.0, description="Dedupe/Resolution confidence")
    timestamp: datetime = Field(default_factory=datetime.utcnow)

# ═══════════════════════════════════════════════════════════════════════════
# GRAPH UPDATE EVENT (Topic: graph-update)
# ═══════════════════════════════════════════════════════════════════════════
class GraphUpdateEvent(BaseModel):
    """
    Emitted by normalization-service or specialized graph extractors.
    Consumed by graph-engine and influence-engine.
    """
    ueid_from: str = Field(..., description="Source node UEID")
    ueid_to: str = Field(..., description="Target node UEID")
    relationship_type: str = Field(..., description="OWNS, DIRECTS, RIVALS, SUPPLIES, etc.")
    tenant_id: str = Field(..., description="Tenant ID")
    properties: Dict[str, Any] = Field(default_factory=dict, description="Edge properties (e.g., share_percentage)")
    confidence: float = Field(default=1.0)
    timestamp: datetime = Field(default_factory=datetime.utcnow)

# ═══════════════════════════════════════════════════════════════════════════
# SIGNAL EVENT (Topic: signals)
# ═══════════════════════════════════════════════════════════════════════════
class Signal(BaseModel):
    """
    Emitted by meta-scoring-service after CERS aggregation.
    Consumed by api-gateway, tts-narrator, alerts-engine.
    """
    signal_id: str = Field(..., description="Unique Signal Artifact ID")
    tenant_id: str = Field(..., description="Target tenant")
    target_ueid: str = Field(..., description="Entity the signal is about")
    signal_type: str = Field(..., description="RISK_SPIKE, OPPORTUNITY, ANOMALY")
    cers_score: int = Field(..., ge=0, le=100, description="Composite Economic Risk Score")
    confidence: float = Field(..., ge=0.0, le=1.0)
    shap_explanations: Dict[str, float] = Field(default_factory=dict, description="Top positive/negative factors")
    narrative: str = Field(..., description="LLM-generated human-readable summary of the signal")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
