apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.username }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: local-path
