apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.username }}-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
    requests.cpu: "8"
    limits.cpu: "8"
    requests.memory: "16Gi"
    limits.memory: "16Gi"
    persistentvolumeclaims: "1"
