enabled: true
replicaCount: 1
image:
  repository: "europe-west3-docker.pkg.dev/project-b63e383c-4a98-418d-837/predator-repo/rtb-engine"
  tag: "latest"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  ENV: "production"
  KAFKA_BOOTSTRAP_SERVERS: "predator-redpanda:9092"
