apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-platform.fullname" . }}
  labels:
    {{- include "mcp-platform.labels" . | nindent 4 }}
data:
  app: {{ .Chart.Name }}
  version: "{{ .Chart.AppVersion }}"
