apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predator-umbrella-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dima1203oleg/predator-analytics.git"
    targetRevision: main
    path: helm/predator-umbrella
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: predator-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
