# Reusable snippet to run e2e tests using docker-compose local environment or kind
# On success it exits 0; on failure, it fails the job

name: Run E2E Tests
on: [workflow_call]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: predator_test
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via docker-compose
        run: |
          docker compose -f docker-compose.yml up -d --build
          sleep 10

      - name: Run smoke tests
        run: |
          docker exec predator_backend pytest -q tests/smoke || { docker compose -f docker-compose.yml down; exit 1; }

      - name: Teardown
        if: always()
        run: |
          docker compose -f docker-compose.yml down
